# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


def _is_non_overlapping_and_dense(t):
    """True when every element of ``t`` names exactly one storage slot.

    Mirrors ``at::is_non_overlapping_and_dense``: two distinct elements never
    share a memory location (no internal overlap) and the tensor covers its
    storage without gaps (dense). Size-1 dimensions are ignored, since their
    stride is irrelevant to which address an element names. A stride-2 slice,
    for example, is overlap-free but not dense, and ATen's fused-optimizer
    fast path rejects it for exactly that reason.
    """
    if t.numel() <= 1:
        return True
    sizes_strides = sorted((s, sz) for sz, s in zip(t.shape, t.stride()) if sz != 1)
    expected = 1
    for stride, size in sizes_strides:
        if stride != expected:
            return False
        expected *= size
    return True


def _strides_match(a, b):
    """ATen's ``_check_tensors_share_sizes_and_strides``: strides of ``a`` and
    ``b`` agree on every dimension whose size is not 1 (a size-1 dimension's
    stride is irrelevant to which element an index names)."""
    if a.shape != b.shape:
        return False
    for size, sa, sb in zip(a.shape, a.stride(), b.stride()):
        if size != 1 and sa != sb:
            return False
    return True


def _storage_view(t):
    """Flat 1-D view of ``t`` in *storage* order.

    The elementwise Adagrad step needs each logical element to line up across
    ``param``/``grad``/``state_sum``. When all three share a shape and a
    non-overlapping-and-dense stride set, walking them in storage order visits
    the same logical element at the same relative position in each, so flat
    indexing on these views is correct for any such layout -- including a
    transposed tensor, which ``is_contiguous()`` would have rejected.
    """
    if t.is_contiguous():
        return t.reshape(-1)
    return t.as_strided((t.numel(),), (1,))


@libentry()
@triton.jit
def _fused_adagrad_kernel(
    param,
    grad,
    state_sum,
    state_step,  # scalar tensor holding the optimizer step (read on-device)
    n: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
    ACC_DTYPE: tl.constexpr,
    lr: tl.constexpr,
    lr_decay: tl.constexpr,
    weight_decay: tl.constexpr,
    eps: tl.constexpr,
    maximize: tl.constexpr,
    has_grad_scale: tl.constexpr,
    grad_scale,
    has_found_inf: tl.constexpr,
    found_inf,
):
    # Get the block index and compute the offsets for this block.
    pid = tle.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n

    # Early skip: if a non-finite gradient was found, leave the buffers untouched.
    # ATen tests ``found_inf == 1`` rather than ``> 0``: any other value (including
    # 2.0) still performs the update, so the comparison has to be exact.
    if has_found_inf:
        found_inf_val = tl.load(found_inf)
        if found_inf_val == 1:
            return

    # Read the optimizer step on-device to avoid a host sync (`.item()`).
    step = tl.load(state_step).to(ACC_DTYPE)

    # Load the parameter, gradient, and running sum of squared gradients.
    param_load = tl.load(param + offsets, mask=mask, other=0.0)
    grad_load = tl.load(grad + offsets, mask=mask, other=0.0)
    state_sum_load = tl.load(state_sum + offsets, mask=mask, other=0.0)

    # Promote low-precision values to the accumulation type for the math (mirrors
    # opmath_type in the reference C++ implementation). fp16/bf16/fp32 accumulate
    # in fp32; fp64 keeps full double precision, which ATen also does -- computing
    # a double parameter in fp32 would lose ~7 digits.
    param_f = param_load.to(ACC_DTYPE)
    grad_f = grad_load.to(ACC_DTYPE)
    state_sum_f = state_sum_load.to(ACC_DTYPE)

    # Gradient unscaling (for AMP). ``grad`` is treated as read-only here: the
    # native CUDA kernel only leaves an unscaled value behind for tail elements
    # when numel is not a multiple of its vector width (4), so that write-back is
    # a vectorization artifact rather than part of the operator contract and is
    # deliberately not reproduced.
    if has_grad_scale:
        grad_scale_val = tl.load(grad_scale)
        grad_f = grad_f / grad_scale_val

    # Handle maximize mode: negate the gradient for gradient ascent.
    if maximize:
        grad_f = -grad_f

    # Apply weight decay (L2 penalty added to the gradient).
    if weight_decay > 0:
        grad_f = grad_f + param_f * weight_decay

    # Accumulate the squared gradient: state_sum += grad * grad
    state_sum_f = state_sum_f + grad_f * grad_f

    # Corrected learning rate: lr / (1 + (step - 1) * lr_decay)
    corrected_lr = lr / (1.0 + (step - 1.0) * lr_decay)

    # Update the parameter: param -= corrected_lr * grad / (sqrt(state_sum) + eps)
    param_f = param_f - corrected_lr * grad_f / (tl.sqrt(state_sum_f) + eps)

    # Store the updated values back, downcasting to the original element dtype.
    tl.store(param + offsets, param_f.to(param_load.dtype), mask=mask)
    tl.store(state_sum + offsets, state_sum_f.to(state_sum_load.dtype), mask=mask)


def _fused_adagrad_run(
    params,
    grads,
    state_sums,
    state_steps,
    *,
    lr,
    lr_decay,
    weight_decay,
    eps,
    maximize,
    grad_scale,
    found_inf,
):
    """Shared driver for the fused Adagrad step.

    Performs one step of the Adagrad optimizer for each parameter:

      corrected_lr = lr / (1 + (step - 1) * lr_decay)
      g  = grad / grad_scale            (only when grad_scale is provided)
      g  = -g                          (only when maximize is set)
      g  = g + weight_decay * param     (only when weight_decay > 0)
      state_sum += g * g
      param = param - corrected_lr * g / (sqrt(state_sum) + eps)

    ``state_steps`` is incremented by the caller; the step value is read on
    device inside the kernel to avoid a host synchronization.  When
    ``found_inf == 1`` the update is skipped entirely (AMP recovery), matching
    ATen's exact comparison -- other nonzero values still apply the update.
    ``grads`` is read-only: only ``params`` and ``state_sums`` are mutated.
    """
    has_grad_scale = grad_scale is not None
    has_found_inf = found_inf is not None
    grad_scale_ptr = grad_scale if has_grad_scale else None
    found_inf_ptr = found_inf if has_found_inf else None

    # Validate the whole batch before touching any buffer. These values drive raw
    # pointer arithmetic in the kernel, and a partially applied step is not
    # recoverable, so every list has to be checked up front rather than lazily
    # inside the launch loop.
    n_params = len(params)
    for name, seq in (
        ("grads", grads),
        ("state_sums", state_sums),
        ("state_steps", state_steps),
    ):
        if len(seq) != n_params:
            raise RuntimeError(
                f"_fused_adagrad_: expected {name} to have the same length as "
                f"params ({n_params}), got {len(seq)}"
            )

    # Mirror ATen's fast-path restriction check
    # (``check_fast_path_restrictions`` in ForeachUtils.h), which the native CUDA
    # kernel runs before its first launch: params[0] fixes the expected dtype and
    # device, and every tensor in params/grads/state_sums must match that
    # dtype/device, be strided, and be non-overlapping and dense; corresponding
    # entries must additionally share sizes and strides. This makes the check
    # *global*: a params list mixing fp32 and fp64 (each entry internally
    # consistent) is rejected exactly as ATen rejects it. All of it happens
    # before any kernel launch, so a rejected batch leaves every buffer
    # untouched -- no partial update.
    if n_params > 0:
        expected_device = params[0].device
        expected_dtype = params[0].dtype
        _SUPPORTED = (torch.float16, torch.bfloat16, torch.float32, torch.float64)
        if expected_dtype not in _SUPPORTED:
            raise RuntimeError(
                "_fused_adagrad_ only supports float16/bfloat16/float32/float64 "
                f"inputs, got {expected_dtype} at index 0"
            )
        for i in range(n_params):
            param, grad, state_sum = params[i], grads[i], state_sums[i]
            for name, tensor in (
                ("param", param),
                ("grad", grad),
                ("state_sum", state_sum),
            ):
                if tensor.dtype != expected_dtype:
                    raise RuntimeError(
                        "params, grads, and state_sums must have same dtype, "
                        f"device, and layout: {name}[{i}] dtype {tensor.dtype} "
                        f"differs from params[0] dtype {expected_dtype}"
                    )
                if tensor.device != expected_device:
                    raise RuntimeError(
                        "params, grads, and state_sums must have same dtype, "
                        f"device, and layout: {name}[{i}] device {tensor.device} "
                        f"differs from params[0] device {expected_device}"
                    )
                if tensor.layout != torch.strided:
                    raise RuntimeError(
                        f"{name}[{i}] must be a strided tensor, got layout "
                        f"{tensor.layout}"
                    )
                if not _is_non_overlapping_and_dense(tensor):
                    raise RuntimeError(
                        f"_fused_adagrad_: {name}[{i}] is not "
                        "non-overlapping-and-dense (internal overlap or gappy "
                        "strides), so it has no well-defined element order"
                    )
            for name, other in (("grad", grad), ("state_sum", state_sum)):
                if other.shape != param.shape:
                    raise RuntimeError(
                        f"_fused_adagrad_: {name}[{i}] shape {tuple(other.shape)} "
                        f"does not match param shape {tuple(param.shape)}"
                    )
                if not _strides_match(param, other):
                    raise RuntimeError(
                        f"_fused_adagrad_: {name}[{i}] strides {other.stride()} "
                        f"do not match param strides {param.stride()}"
                    )

    # ``state_steps``: ATen passes each step tensor's raw data pointer to the
    # kernel, which blindly reinterprets it as ``float``. That makes float32 the
    # only honest contract; other dtypes happen to work in ATen only when their
    # bit pattern reinterprets to the right value (int64 1 reads as a denormal ~0
    # and still "works" for step==1, but int32 3 gives corrected_lr ~= lr instead
    # of lr/3). We read the step in its true dtype, so any dtype whose values are
    # integral would work here -- but to keep this operator's contract aligned
    # with the optimizer API (``torch.optim.Adagrad(fused=True)`` stores
    # ``state["step"]`` as a float32 scalar tensor) we accept only float32 and
    # reject everything else up front, before the first launch.
    for i, state_step in enumerate(state_steps):
        if state_step.dtype != torch.float32:
            raise RuntimeError(
                "state_steps must contain float32 scalar tensors (one element "
                f"holding the optimizer step), got dtype {state_step.dtype} at "
                f"index {i}"
            )
        if state_step.numel() != 1:
            raise RuntimeError(
                "state_steps must contain 1-element tensors, got numel "
                f"{state_step.numel()} at index {i}"
            )
        if state_step.device != params[0].device:
            raise RuntimeError(
                "Expected all tensors to be on the same device, but got "
                f"state_steps is on {state_step.device}, different from other "
                f"tensors on {params[0].device}"
            )

    # ``found_inf`` is read on-device inside the kernel; deliberately no
    # ``.item()`` here, which would synchronize on every AMP step and break
    # CUDA graph capture.

    for i in range(len(params)):
        param = params[i]
        grad = grads[i]
        state_sum = state_sums[i]
        state_step = state_steps[i]

        n = param.numel()
        # Nothing to update for an empty parameter, and a zero-sized grid is not
        # a valid launch.
        if n == 0:
            continue

        # Pick a block size that is a power of two, large enough for occupancy
        # but bounded to avoid register pressure.
        BLOCK_SIZE = triton.next_power_of_2(n)
        BLOCK_SIZE = max(BLOCK_SIZE, 128)
        BLOCK_SIZE = min(BLOCK_SIZE, 4096)

        grid = (triton.cdiv(n, BLOCK_SIZE),)

        # fp64 params accumulate in fp64; everything else in fp32.
        acc_dtype = tl.float64 if param.dtype == torch.float64 else tl.float32

        # Walk all three operands in storage order. They were validated to be
        # non-overlapping and dense with matching strides, so this line-up is
        # exact for non-contiguous layouts (a transpose, say) as well.
        _fused_adagrad_kernel[grid](
            _storage_view(param),
            _storage_view(grad),
            _storage_view(state_sum),
            state_step,
            n,
            BLOCK_SIZE,
            acc_dtype,
            lr,
            lr_decay,
            weight_decay,
            eps,
            maximize,
            has_grad_scale,
            grad_scale_ptr,
            has_found_inf,
            found_inf_ptr,
        )


def _fused_adagrad_(
    params,
    grads,
    state_sums,
    state_steps,
    *,
    lr: float = 1e-2,
    lr_decay: float = 0.0,
    weight_decay: float = 0.0,
    eps: float = 1e-10,
    maximize: bool = False,
    grad_scale=None,
    found_inf=None,
):
    """In-place fused Adagrad step.

    Mirrors ``aten::_fused_adagrad_``: the ``params`` and ``state_sums`` tensors
    are updated in place and nothing is returned. ``grads`` is not modified.
    """
    logger.debug("GEMS FUSED_ADAGRAD_")

    _fused_adagrad_run(
        params,
        grads,
        state_sums,
        state_steps,
        lr=lr,
        lr_decay=lr_decay,
        weight_decay=weight_decay,
        eps=eps,
        maximize=maximize,
        grad_scale=grad_scale,
        found_inf=found_inf,
    )

    return None
