# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib
import logging
import os
from functools import lru_cache
from typing import Any, Callable, Mapping, Tuple

import torch

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.code_cache import code_cache_dir
from flag_gems.utils.code_utils import IndentedBuffer, write_atomic

logger = logging.getLogger(__name__)


def generate_imports(code: IndentedBuffer) -> IndentedBuffer:
    code.writeline("import torch")
    code.writeline("import triton")
    code.writeline("import triton.language as tl")
    code.newline()
    code.writeline("from flag_gems.utils import libentry")
    code.writeline("from flag_gems.utils import triton_lang_extension as ext")
    code.newline()
    code.newline()
    return code


def generate_kernel(
    rank: int, grad_ndim: int, kernel_name: str, code: IndentedBuffer
) -> IndentedBuffer:
    """Emit the coordinate-unravelling kernel.

    ``grad_ndim`` is the rank of ``grad`` and gives the number of extents the flat
    coordinate is unravelled over; ``rank`` is ``self.ndim`` and bounds how many of
    those coordinates are actually written. The native op derives its extents from
    ``grad`` while emitting ``self.ndim`` rows, so the two can differ.
    """
    code.newline()
    code.writeline("@libentry()")
    code.writeline("@triton.jit")
    code.writeline(f"def {kernel_name}(")
    with code.indent():
        args = ["index_ptr, ", "out_ptr, ", "nnz, ", "dim, ", "idx_stride, "]
        args += [f"dim_size{i}, " for i in range(grad_ndim)]
        args += ["BLOCK_SIZE: tl.constexpr, "]
        code.writelines(args)
    code.writeline("):")

    with code.indent():
        code.writeline("pid = ext.program_id(0)")
        code.writeline(
            "offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE).to(tl.int64)"
        )
        code.writeline("mask = offs < nnz")
        # ``idx_stride`` is 1 for a normal index and 0 when ``index`` holds a single
        # element that broadcasts to every non-zero. That mirrors the native path,
        # where ``index.reshape(-1)`` of length 1 is assigned to a row of length
        # ``grad.numel()`` and therefore repeats.
        code.writeline(
            "idx_gather = tl.load(index_ptr + offs * idx_stride, mask=mask, other=0).to(tl.int64)"
        )
        code.writeline("cur = offs")
        for d in range(grad_ndim - 1, -1, -1):
            code.writeline(f"coord{d} = cur % dim_size{d}")
            code.writeline(f"cur = cur // dim_size{d}")
            if d < rank:
                code.writeline(
                    f"store_val{d} = tl.where({d} == dim, idx_gather, coord{d})"
                )
                code.writeline(
                    f"tl.store(out_ptr + {d} * nnz + offs, store_val{d}, mask=mask)"
                )
    code.newline()
    code.newline()
    return code


def generate_wrapper(
    rank: int,
    grad_ndim: int,
    wrapper_name: str,
    kernel_name: str,
    code: IndentedBuffer,
) -> IndentedBuffer:
    code.writeline(
        f"def {wrapper_name}(index_flat, out, nnz, dim, idx_stride, dim_count, dim_sizes):"
    )
    with code.indent():
        code.writeline("BLOCK_SIZE = 1024")
        code.writeline("grid = (triton.cdiv(nnz, BLOCK_SIZE),)")
        code.writeline(f"{kernel_name}[grid](")
        with code.indent():
            args = ["index_flat, ", "out, ", "nnz, ", "dim, ", "idx_stride, "]
            args += [f"dim_sizes[{i}], " for i in range(grad_ndim)]
            args += ["BLOCK_SIZE, "]
            code.writelines(args)
        code.writeline(")")
    code.newline()
    code.newline()
    return code


def generate_code(
    inputs: Tuple[Any], wrapper_name: str, kernel_name: str, code: IndentedBuffer
) -> IndentedBuffer:
    rank, grad_ndim = inputs[0], inputs[1]
    code = generate_imports(code)
    code = generate_kernel(rank, grad_ndim, kernel_name, code)
    code = generate_wrapper(rank, grad_ndim, wrapper_name, kernel_name, code)
    return code


class GatherSparseBackwardFunction:
    def __init__(self):
        self.pid = os.getpid()
        self.overloads: Mapping[str, Callable] = {}

    # Positional arguments of the generated wrapper.
    _RANK_IDX = 5
    _DIM_SIZES_IDX = 6

    def __call__(self, *args, **kwargs):
        key = self.arg_key(*args)
        if key in self.overloads:
            overload = self.overloads[key]
        else:
            rank = args[self._RANK_IDX]
            grad_ndim = len(args[self._DIM_SIZES_IDX])
            code = IndentedBuffer()
            code = generate_code(
                (rank, grad_ndim),
                "_gather_sparse_backward_wrapper",
                "_gather_sparse_backward_kernel",
                code,
            )
            file_name = f"_gather_sparse_backward_rank_{key}.py"
            file_path = code_cache_dir() / file_name
            write_atomic(file_path, code.getvalue())

            spec = importlib.util.spec_from_file_location(
                f"_gather_sparse_backward_gen_rank_{key}", file_path
            )
            m = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(m)
            overload = getattr(m, "_gather_sparse_backward_wrapper")
            self.overloads[key] = overload

        return overload(*args, **kwargs)

    def arg_key(self, *args):
        return f"{len(args[self._DIM_SIZES_IDX])}_{args[self._RANK_IDX]}"


@lru_cache(maxsize=1)
def _kernel_func() -> "GatherSparseBackwardFunction":
    # Lazily instantiated inside a function (not a module-level global) so the
    # code-gen overload cache lives on the returned singleton, per reviewer
    # guidance to avoid module-level global state.
    return GatherSparseBackwardFunction()


def _gather_sparse_backward(self, dim, index, grad):
    logger.debug("GEMS _GATHER_SPARSE_BACKWARD")

    ndim = self.ndim

    # ATen has two dedicated scalar paths and they are *not* symmetric. From
    # aten/src/ATen/native/TensorAdvancedIndexing.cpp:
    #
    #   if (self.ndimension() == 0)
    #     return _sparse_coo_tensor_unsafe({0, grad.numel()}, grad, self.sizes());
    #   if (grad.ndimension() == 0)
    #     return _sparse_coo_tensor_unsafe(index.view({1, 1}), grad, self.sizes());
    #
    # A 0-dim ``self`` is checked first. It ignores ``index`` and ``dim``
    # completely, keeps *every* grad value and emits a ``(0, grad.numel())``
    # index tensor, so the result has sparse_dim 0.
    #
    # A 0-dim ``grad`` on a non-scalar ``self`` keeps the real
    # ``index.view(1, 1)`` coordinate -- a nonzero scalar index stays nonzero --
    # with a single value. Both paths must run before the equal-rank check, which
    # does not apply to them.
    if ndim == 0:
        sparse_indices = torch.empty(
            (0, grad.numel()), dtype=torch.int64, device=index.device
        )
        return torch.sparse_coo_tensor(
            sparse_indices, grad, self.size(), device=self.device
        )

    if grad.ndim == 0:
        sparse_indices = index.reshape(1, 1)
        if sparse_indices.dtype != torch.int64:
            sparse_indices = sparse_indices.to(torch.int64)
        return torch.sparse_coo_tensor(
            sparse_indices, grad, self.size(), device=self.device
        )

    # ``grad`` supplies the non-zero count and, for non-gather dimensions, the
    # extents the flat coordinate is unravelled over. ``index`` only contributes
    # the coordinate along ``dim``, as ``index.reshape(-1)``; when it holds a
    # single element that value broadcasts across every non-zero, exactly like
    # the native row assignment.
    nnz = grad.numel()

    # The sparse values are simply the flattened gradient.
    values = grad.reshape(-1)

    # An empty grad gives nnz == 0. The native op allocates its index tensor
    # before the ``grad_numel > 0`` guard, so the row count here is always
    # ``self.ndim`` regardless of the ranks involved.
    if nnz == 0:
        sparse_indices = torch.empty((ndim, 0), dtype=torch.int64, device=index.device)
        out = torch.sparse_coo_tensor(
            sparse_indices, values, self.size(), device=self.device
        )
        return out

    # The native op unravells each flat coordinate over the extents of ``grad``
    # (its ``n_above`` starts at ``grad.numel()`` even though the loop runs only
    # ``self.ndim`` times) and writes the leading ``self.ndim`` rows, so a
    # higher-rank ``grad`` still contributes to the coordinates. A lower-rank
    # ``grad`` would index past its own extents, which the native op rejects --
    # but only when there is something to unravel, hence the nnz == 0 early exit
    # above.
    if grad.ndim < ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-grad.ndim}, {grad.ndim - 1}], but got {grad.ndim})"
        )

    index_flat = index.reshape(-1).contiguous()
    # A single index element broadcasts to all nnz entries (stride 0 in the
    # kernel); otherwise it must line up one-to-one with the gradient.
    if index_flat.numel() == 1:
        idx_stride = 0
    elif index_flat.numel() == nnz:
        idx_stride = 1
    else:
        raise IndexError(
            f"index must have 1 or {nnz} elements to match the gradient, "
            f"got {index_flat.numel()}"
        )

    # The native op validates nothing about ``dim``: the row is only overwritten
    # when some ``i`` equals ``dim``, so a dim outside ``[0, ndim)`` simply never
    # matches and every coordinate stays at its unravelled value. Negative dims
    # are folded first (its loop runs ``i`` in ``range(ndim)``).
    dim = dim if dim >= 0 else dim + ndim

    if index_flat.dtype != torch.int64:
        index_flat = index_flat.to(torch.int64)

    sparse_indices = torch.empty((ndim, nnz), dtype=torch.int64, device=index.device)

    dim_sizes = tuple(int(s) for s in grad.shape)
    with torch_device_fn.device(index.device):
        _kernel_func()(
            index_flat, sparse_indices, nnz, dim, idx_stride, ndim, dim_sizes
        )

    out = torch.sparse_coo_tensor(
        sparse_indices, values, self.size(), device=self.device
    )
    return out
