# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from collections import namedtuple

import torch
import triton
import triton.language as tl

from flag_gems.ops.linalg_lu_factor import _linalg_lu_factor_impl
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _lu_info_kernel(
    LU,
    INFO,
    M,
    N,
    stride_batch,  # bytes between batch elements (element count), as int64
    K_MAX: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """Compute the ``info`` tensor for an LU factorization.

    ``info[b]`` is the 1-indexed position of the first exactly-zero pivot on
    the U diagonal of ``LU[b]`` (i.e. ``LU[b, j, j] == 0`` for the smallest ``j``
    in ``[0, k)`` where ``k = min(M, N)``), or ``0`` if every U pivot is
    nonzero. This mirrors the cuSOLVER convention: a nonzero ``info`` flags a
    singular factor (the matrix could not be factored into a nonsingular U),
    while ``info == 0`` means success.

    Only an *exact* zero counts. ``NaN`` and ``Inf`` pivots are **not** singular:
    ``torch.linalg.lu_factor_ex`` reports ``info == 0`` for a matrix whose
    diagonal is ``inf`` or ``nan`` (measured on both CPU and CUDA), so treating
    them as singular would report a failure where ATen reports success.
    """
    pid_b = tl.program_id(0)

    info_val = tl.zeros((), dtype=tl.int32)
    for j in tl.range(0, K_MAX):
        # LU[b, j, j] for a row-major (..., M, N) tensor: offset = b*strd + j*N + j
        diag_off = pid_b.to(tl.int64) * stride_batch + j * N + j
        pivot = tl.load(LU + diag_off)
        # cuSOLVER reports the 1-indexed position of the first pivot that is
        # exactly zero. NaN compares unequal to itself, so `== 0.0` already
        # excludes it (and any Inf) without a separate test.
        is_singular = pivot == 0.0
        # Record the *first* singular index; once info_val is set, keep it.
        already_set = info_val != 0
        info_val = tl.where(already_set, info_val, tl.where(is_singular, j + 1, 0))
    tl.store(INFO + pid_b, info_val)


def _lu_with_info_impl(input, pivot=True, check_errors=True):
    # Named result tuple scoped to the implementation so it is not a module-level
    # global (reviewer preference: keep per-call state out of module scope).
    LuWithInfoResult = namedtuple("LuWithInfoResult", ["LU", "pivots", "info"])
    if input.dim() < 2:
        raise RuntimeError(
            "torch._lu_with_info: Expected input to have at least 2 "
            f"dimensions, got {input.dim()}"
        )
    if input.dtype not in (torch.float32, torch.float64):
        raise NotImplementedError(
            "FlagGems _lu_with_info currently supports float32 and float64 "
            f"only, got {input.dtype}"
        )
    m, n = input.shape[-2], input.shape[-1]
    batch_shape = input.shape[:-2]
    k = min(m, n)
    if input.numel() == 0:
        # Any zero dimension -- an empty matrix like (0, 3), a zero-sized row or
        # column like (3, 0), or a zero-sized batch dimension like (0, 3, 3) /
        # (2, 0, 3, 3) -- gives an empty factorization: LU keeps the input
        # shape, pivots are empty along the k axis, and info is 0 (success) for
        # every batch element. This matches ``torch._lu_with_info`` on empty
        # inputs, including the batch==0 forms that never reach the factorizer.
        lu = input.clone()
        pivots = torch.empty(batch_shape + (k,), device=input.device, dtype=torch.int32)
        info = torch.zeros(batch_shape, device=input.device, dtype=torch.int32)
        return LuWithInfoResult(lu, pivots, info)

    # Core LU factorization is the Triton implementation shared with
    # ``linalg_lu_factor`` (panel-blocked partial-pivoting LU). It produces
    # the compact LU storage and int32 pivots; we then derive the ``info``
    # tensor with a dedicated Triton kernel that scans the U diagonal.
    lu, pivots = _linalg_lu_factor_impl(input, pivot=pivot)

    batch = lu.numel() // (m * n)
    info = torch.zeros(batch_shape, device=lu.device, dtype=torch.int32)

    if batch > 0:
        # LU is contiguous (..., M, N); stride between batch elements in elems.
        stride_batch = m * n
        block = triton.next_power_of_2(k)
        with torch_device_fn.device(lu.device):
            _lu_info_kernel[(batch,)](
                lu,
                info,
                m,
                n,
                stride_batch,
                K_MAX=k,
                BLOCK=block,
                num_warps=4,
            )
    return LuWithInfoResult(lu, pivots, info)


def _lu_with_info(input, pivot=True, check_errors=True):
    logger.debug("GEMS _LU_WITH_INFO")
    return _lu_with_info_impl(input, pivot, check_errors)
