# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def batch_norm_gather_stats_kernel(
    mean_ptr,
    invstd_ptr,
    running_mean_ptr,
    running_var_ptr,
    out_mean_ptr,
    out_invstd_ptr,
    num_segments: tl.constexpr,
    C: tl.constexpr,
    momentum,
    eps,
    has_running_mean: tl.constexpr,
    BLOCK_SEGMENTS: tl.constexpr,
):
    # Each program handles one channel
    c = tl.program_id(0)

    # Load mean and invstd for all segments for this channel
    seg_offsets = tl.arange(0, BLOCK_SEGMENTS)
    mask = seg_offsets < num_segments

    # mean_ptr layout: [num_segments, C], stride = C
    mean_vals = tl.load(mean_ptr + seg_offsets * C + c, mask=mask, other=0.0).to(
        tl.float32
    )
    invstd_vals = tl.load(invstd_ptr + seg_offsets * C + c, mask=mask, other=0.0).to(
        tl.float32
    )

    # Compute per-segment variance: var_i = 1/(invstd_i^2) - eps
    var_vals = 1.0 / (invstd_vals * invstd_vals) - eps

    # Global mean = mean of per-segment means
    inv_num_segments = 1.0 / num_segments
    global_mean = tl.sum(mean_vals, axis=0) * inv_num_segments

    # Global variance using parallel variance formula:
    # global_var = mean(var_i) + mean((mean_i - global_mean)^2)
    mean_var = tl.sum(var_vals, axis=0) * inv_num_segments
    diff = mean_vals - global_mean
    mean_sq_diff = tl.sum(diff * diff, axis=0) * inv_num_segments
    global_var = mean_var + mean_sq_diff

    # Global invstd
    global_invstd = 1.0 / tl.sqrt(global_var + eps)

    # Store outputs
    tl.store(out_mean_ptr + c, global_mean)
    tl.store(out_invstd_ptr + c, global_invstd)

    # Update running stats if provided
    if has_running_mean:
        old_rm = tl.load(running_mean_ptr + c).to(tl.float32)
        new_rm = (1.0 - momentum) * old_rm + momentum * global_mean
        tl.store(running_mean_ptr + c, new_rm)

        old_rv = tl.load(running_var_ptr + c).to(tl.float32)
        new_rv = (1.0 - momentum) * old_rv + momentum * global_var
        tl.store(running_var_ptr + c, new_rv)


def batch_norm_gather_stats(
    input: Tensor,
    mean: Tensor,
    invstd: Tensor,
    running_mean,
    running_var,
    momentum: float,
    eps: float,
    count: int,
):
    logger.debug("GEMS BATCH_NORM_GATHER_STATS")

    num_segments = mean.shape[0]
    C = mean.shape[1]

    # Allocate outputs (always float32)
    out_mean = torch.empty(C, dtype=torch.float32, device=mean.device)
    out_invstd = torch.empty(C, dtype=torch.float32, device=mean.device)

    # Determine BLOCK_SEGMENTS (next power of 2 >= num_segments)
    BLOCK_SEGMENTS = triton.next_power_of_2(num_segments)

    has_running_mean = running_mean is not None and running_var is not None

    # Use dummy pointer if no running stats
    running_mean_ptr = running_mean if has_running_mean else out_mean
    running_var_ptr = running_var if has_running_mean else out_invstd

    grid = (C,)

    with torch_device_fn.device(input.device):
        batch_norm_gather_stats_kernel[grid](
            mean,
            invstd,
            running_mean_ptr,
            running_var_ptr,
            out_mean,
            out_invstd,
            num_segments=num_segments,
            C=C,
            momentum=momentum,
            eps=eps,
            has_running_mean=has_running_mean,
            BLOCK_SEGMENTS=BLOCK_SEGMENTS,
        )

    return out_mean, out_invstd
