# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _inner_gemm_kernel(
    a_ptr,
    b_ptr,
    c_ptr,
    M,
    N,
    K,
    stride_am,
    stride_ak,
    stride_bn,
    stride_bk,
    stride_cm,
    stride_cn,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
    GROUP_M: tl.constexpr,
    HAS_MASK: tl.constexpr,
    IS_FP32: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    """Tiled GEMM computing ``inner(A, B)[m, n] = sum_k A[m, k] * B[n, k]``.

    ``A`` and ``B`` are both laid out as ``(rows, K)``, so ``B`` is the second
    operand already transposed; only its row stride is needed to stride ``K``.
    ``BLOCK_M``/``BLOCK_N``/``BLOCK_K`` and ``GROUP_M`` are performance critical:
    ``GROUP_M`` swizzles the tile order so neighbouring programs share ``A``/``B``
    panels through L2.
    """
    pid = tl.program_id(0)
    num_pid_m = tl.cdiv(M, BLOCK_M)
    num_pid_n = tl.cdiv(N, BLOCK_N)
    num_pid_in_group = GROUP_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_M
    group_size_m = tl.minimum(num_pid_m - first_pid_m, GROUP_M)
    pid_m = first_pid_m + ((pid % num_pid_in_group) % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    a_ptrs = a_ptr + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak
    b_ptrs = b_ptr + offs_n[None, :] * stride_bn + offs_k[:, None] * stride_bk

    mask_m = offs_m[:, None] < M
    mask_n = offs_n[None, :] < N

    if IS_FP64:
        # fp64 has no tensor-core path, so the accumulator must stay fp64 for
        # both the arithmetic and the loop-carried type to agree.
        acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float64)
    else:
        acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)
    for k0 in range(0, K, BLOCK_K):
        if HAS_MASK:
            k_remaining = K - k0
            a = tl.load(
                a_ptrs, mask=mask_m & (offs_k[None, :] < k_remaining), other=0.0
            )
            b = tl.load(
                b_ptrs, mask=(offs_k[:, None] < k_remaining) & mask_n, other=0.0
            )
        else:
            # Every dimension divides its tile exactly, so the masks are
            # redundant and skipping them removes a compare+select per load.
            a = tl.load(a_ptrs)
            b = tl.load(b_ptrs)
        if IS_FP64:
            # fp64 has no tensor-core path, so the accumulator and the dot
            # output type must both stay fp64.
            acc = tl.dot(a, b, acc, input_precision="ieee", out_dtype=tl.float64)
        elif IS_FP32:
            # tf32x3 splits each fp32 operand into three tf32 slices and
            # combines them with tensor-core dots, so the fp32 accuracy is kept
            # (~2^-24 per product) without falling back to the slow fp32 FMA
            # path. Plain tf32 would be faster but loses 13 mantissa bits,
            # which the fp32 reduction tolerance rejects.
            acc = tl.dot(a, b, acc, input_precision="tf32x3")
        else:
            acc = tl.dot(a, b, acc)
        a_ptrs += BLOCK_K * stride_ak
        b_ptrs += BLOCK_K * stride_bk

    c_ptrs = c_ptr + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn
    if HAS_MASK:
        tl.store(c_ptrs, acc.to(c_ptr.dtype.element_ty), mask=mask_m & mask_n)
    else:
        tl.store(c_ptrs, acc.to(c_ptr.dtype.element_ty))


@libentry()
@triton.jit
def _inner_dot_kernel(
    a_ptr,
    b_ptr,
    mid_ptr,
    K,
    BLOCK_SIZE: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    """Strided 1-D contraction writing one partial sum per program.

    ``IS_FP64`` selects the accumulation dtype: fp64 inputs have no fast
    lower-precision path available, so they accumulate in fp64. Every other
    dtype accumulates in fp32, matching eager PyTorch's reduction precision.
    """
    pid = tl.program_id(0)
    num_programs = tl.num_programs(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)

    if IS_FP64:
        acc = tl.zeros((BLOCK_SIZE,), dtype=tl.float64)
        for k0 in range(0, K, num_programs * BLOCK_SIZE):
            cur = k0 + offs
            mask = cur < K
            a = tl.load(a_ptr + cur, mask=mask, other=0.0)
            b = tl.load(b_ptr + cur, mask=mask, other=0.0)
            acc += a * b
    else:
        acc = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)
        for k0 in range(0, K, num_programs * BLOCK_SIZE):
            cur = k0 + offs
            mask = cur < K
            a = tl.load(a_ptr + cur, mask=mask, other=0.0).to(tl.float32)
            b = tl.load(b_ptr + cur, mask=mask, other=0.0).to(tl.float32)
            acc += a * b

    tl.store(mid_ptr + pid, tl.sum(acc, axis=0))


@libentry()
@triton.jit
def _inner_dot_reduce_kernel(mid_ptr, c_ptr, n_blocks, BLOCK_N: tl.constexpr):
    """Tree-reduce the per-program partial sums into the scalar output."""
    offs = tl.arange(0, BLOCK_N)
    mask = offs < n_blocks
    partials = tl.load(mid_ptr + offs, mask=mask, other=0.0)
    tl.store(c_ptr, tl.sum(partials, axis=0).to(c_ptr.dtype.element_ty))


def _select_block_config(M, N, K, dtype):
    """Pick GEMM tile sizes.

    64x64x32 measured fastest across the fp16/fp32/bf16 cases on the H20
    target; the larger fp32 shapes prefer 5 pipeline stages and the fp16 large
    shapes prefer 8 warps at 3 stages. The narrow shapes fall back to a 16x16
    tile so a single program already covers the whole tile.
    """
    large = M >= 512 and N >= 512 and K >= 512
    if M < 16 or N < 16:
        return 16, 16, 32, 4, 3
    if dtype == torch.float16 and large:
        return 64, 64, 32, 8, 3
    if dtype == torch.float32 and large:
        return 64, 64, 32, 4, 5
    return 64, 64, 32, 4, 4


def inner(input: torch.Tensor, other: torch.Tensor) -> torch.Tensor:
    """Compute the inner product of two tensors.

    Contracts the last dimension of ``input`` with the last dimension of
    ``other``, keeping the leading dimensions of each operand per-side without
    broadcasting, which is the matrix product ``input @ other.transpose(-1, -2)``
    with the degenerate cases handled separately:

    * both 1-D      -> scalar dot product
    * one 0-D       -> outer-product scaling (no contraction dimension)
    * otherwise     -> fused strided GEMM over the flattened operands
    """
    logger.debug("GEMS INNER")

    if input.dim() == 0 and other.dim() == 0:
        return (input * other).reshape(())

    if input.dtype != other.dtype:
        raise RuntimeError("both inputs should have same dtype")

    # A 0-D operand has no contraction axis, so inner degenerates to scaling the
    # other operand by the scalar.
    if input.dim() == 0:
        return (other * input).reshape(other.shape)
    if other.dim() == 0:
        return (input * other).reshape(input.shape)

    if input.size(-1) != other.size(-1):
        raise RuntimeError(
            "inner() the last dimension must match on both input tensors but "
            f"got shapes {list(input.shape)} and {list(other.shape)}"
        )

    out_dtype = input.dtype
    device = input.device

    if input.dim() == 1 and other.dim() == 1:
        is_fp64 = out_dtype == torch.float64
        # The per-program partials are fp32 (or fp64 for fp64 inputs) and the
        # reduce kernel writes the final scalar straight into the output dtype,
        # so the result needs no separate cast. `empty` is used because the
        # reduce kernel always stores the value, including for k == 0.
        mid_dtype = torch.float64 if is_fp64 else torch.float32
        out = torch.empty((), dtype=out_dtype, device=device)
        k = input.numel()
        if k == 0:
            return torch.zeros((), dtype=out_dtype, device=device)
        # 64 programs x 64 lanes saturates the reduction without paying for a
        # second launch; a single wide program serializes the loop.
        block_size = 64
        grid = (min(triton.cdiv(k, block_size), 64),)
        mid = torch.empty(grid[0], dtype=mid_dtype, device=device)
        with torch_device_fn.device(device):
            _inner_dot_kernel[grid](
                input, other, mid, k, BLOCK_SIZE=block_size, IS_FP64=is_fp64
            )
            _inner_dot_reduce_kernel[(1,)](
                mid,
                out,
                grid[0],
                BLOCK_N=triton.next_power_of_2(grid[0]),
            )
        return out

    k = input.size(-1)
    out_shape = input.shape[:-1] + other.shape[:-1]
    # An empty contraction dimension is a well-defined all-zero reduction, and
    # `reshape(-1, 0)` is ambiguous, so short-circuit before flattening.
    if k == 0:
        return torch.zeros(out_shape, dtype=out_dtype, device=device)
    a2 = input.reshape(-1, k)
    b2 = other.reshape(-1, k)
    m = a2.shape[0]
    n = b2.shape[0]

    out = torch.empty((m, n), dtype=out_dtype, device=device)
    if m == 0 or n == 0:
        return out.view(out_shape)

    block_m, block_n, block_k, num_warps, num_stages = _select_block_config(
        m, n, k, out_dtype
    )
    grid = (triton.cdiv(m, block_m) * triton.cdiv(n, block_n),)
    # Masks are redundant when every dimension divides its tile exactly.
    has_mask = not (m % block_m == 0 and n % block_n == 0 and k % block_k == 0)
    with torch_device_fn.device(device):
        _inner_gemm_kernel[grid](
            a2,
            b2,
            out,
            m,
            n,
            k,
            a2.stride(0),
            a2.stride(1),
            b2.stride(0),
            b2.stride(1),
            out.stride(0),
            out.stride(1),
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            BLOCK_K=block_k,
            GROUP_M=8,
            HAS_MASK=has_mask,
            IS_FP32=out_dtype == torch.float32,
            IS_FP64=out_dtype == torch.float64,
            num_warps=num_warps,
            num_stages=num_stages,
        )
    return out.view(out_shape)
