# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.contiguous import contiguous
from flag_gems.ops.copy import copy_
from flag_gems.ops.sort import sort_stable
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def canonicalize_nan_kernel(inp, out, n_elements, BLOCK_SIZE: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    values = tl.load(inp + offsets, mask=mask)
    values = tl.where(values != values, float("nan"), values)
    tl.store(out + offsets, values, mask=mask)


@libentry()
@triton.jit
def gather_sorted_values_kernel(
    inp, indices, out, n_elements, n_cols, BLOCK_SIZE: tl.constexpr
):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    rows = tl.load(indices + offsets, mask=mask, other=0)
    values = tl.load(inp + rows * n_cols + offsets % n_cols, mask=mask)
    tl.store(out + offsets, values, mask=mask)


@triton.jit
def _xor_peer(
    x, step: tl.constexpr, BLOCK_ROWS: tl.constexpr, BLOCK_COLS: tl.constexpr
):
    log_rows: tl.constexpr = BLOCK_ROWS.bit_length() - 1
    shape: tl.constexpr = [BLOCK_COLS] + [2] * log_rows
    hypercube = tl.reshape(x, shape)
    pair_xor = tl.xor_sum(hypercube, log_rows - step, keep_dims=True)
    pair_xor = tl.reshape(tl.broadcast_to(pair_xor, shape), x.shape)
    return x ^ pair_xor


@libentry()
@triton.jit
def msort_kernel(
    inp,
    out,
    n_rows,
    n_cols,
    pad_value,
    BLOCK_ROWS: tl.constexpr,
    BLOCK_COLS: tl.constexpr,
):
    col_offsets = tl.program_id(0) * BLOCK_COLS + tl.arange(0, BLOCK_COLS)
    row_offsets = tl.arange(0, BLOCK_ROWS)
    offsets = row_offsets[None, :] * n_cols + col_offsets[:, None]
    mask = (row_offsets[None, :] < n_rows) & (col_offsets[:, None] < n_cols)
    values = tl.load(inp + offsets, mask=mask, other=pad_value)

    if inp.dtype.element_ty.is_floating():
        if inp.dtype.element_ty == tl.float64:
            bits = values.to(tl.uint64, bitcast=True)
            sign_bit = 0x8000000000000000
            max_key = 0xFFFFFFFFFFFFFFFF
        elif inp.dtype.element_ty == tl.float32:
            bits = values.to(tl.uint32, bitcast=True)
            sign_bit = 0x80000000
            max_key = 0xFFFFFFFF
        else:
            bits = values.to(tl.uint16, bitcast=True).to(tl.uint32)
            sign_bit = 0x8000
            max_key = 0xFFFF
        keys = tl.where((bits & sign_bit) != 0, (~bits) & max_key, bits ^ sign_bit)
        keys = tl.where((values != values) | ~mask, max_key, keys)
        original_rows = tl.broadcast_to(row_offsets[None, :], values.shape)
        for stage in tl.static_range(1, BLOCK_ROWS.bit_length()):
            for step in tl.static_range(stage - 1, -1, -1):
                peer_keys = _xor_peer(keys, step, BLOCK_ROWS, BLOCK_COLS)
                peer_rows = _xor_peer(original_rows, step, BLOCK_ROWS, BLOCK_COLS)
                peer_bits = _xor_peer(bits, step, BLOCK_ROWS, BLOCK_COLS)
                less = (keys < peer_keys) | (
                    (keys == peer_keys) & (original_rows < peer_rows)
                )
                choose_min = ((row_offsets & (1 << stage)) == 0) == (
                    (row_offsets & (1 << step)) == 0
                )
                take_peer = tl.where(choose_min[None, :], ~less, less)
                keys = tl.where(take_peer, peer_keys, keys)
                original_rows = tl.where(take_peer, peer_rows, original_rows)
                bits = tl.where(take_peer, peer_bits, bits)
        if inp.dtype.element_ty == tl.float64:
            values = bits.to(tl.float64, bitcast=True)
        elif inp.dtype.element_ty == tl.float32:
            values = bits.to(tl.float32, bitcast=True)
        else:
            values = bits.to(tl.uint16).to(inp.dtype.element_ty, bitcast=True)
        tl.store(out + offsets, values, mask=mask)
    else:
        values = values.to(tl.int64)
        values = tl.sort(values, dim=1, descending=False)
        tl.store(out + offsets, values, mask=mask)


def _pad_value(dtype):
    if dtype.is_floating_point:
        return float("inf")
    if dtype == torch.bool:
        return True
    return torch.iinfo(dtype).max


def _msort_contiguous(inp, out):
    if inp.ndim == 0:
        copy_(out, inp)
        return

    n_rows = inp.shape[0]
    if inp.numel() == 0 or n_rows == 1:
        copy_(out, inp)
        return

    # Triton's bitonic sort is fastest for the common, bounded first dimension.
    # Keep the existing radix implementation as the large-dimension fallback.
    if n_rows > 512:
        radix_inp = inp
        if inp.dtype.is_floating_point:
            radix_inp = torch.empty_like(inp)
            block_size = 1024
            with torch_device_fn.device(inp.device):
                canonicalize_nan_kernel[(triton.cdiv(inp.numel(), block_size),)](
                    inp, radix_inp, inp.numel(), BLOCK_SIZE=block_size
                )
        values, indices = sort_stable(radix_inp, stable=False, dim=0, descending=False)
        if inp.dtype.is_floating_point:
            indices = contiguous(indices)
            with torch_device_fn.device(inp.device):
                gather_sorted_values_kernel[(triton.cdiv(inp.numel(), 1024),)](
                    inp,
                    indices,
                    out,
                    inp.numel(),
                    inp.numel() // n_rows,
                    BLOCK_SIZE=1024,
                )
        else:
            copy_(out, values)
        return

    n_cols = inp.numel() // n_rows
    block_rows = triton.next_power_of_2(n_rows)
    block_cols = min(64, max(1, 8192 // block_rows))
    grid = (triton.cdiv(n_cols, block_cols),)
    with torch_device_fn.device(inp.device):
        msort_kernel[grid](
            inp,
            out,
            n_rows,
            n_cols,
            _pad_value(inp.dtype),
            BLOCK_ROWS=block_rows,
            BLOCK_COLS=block_cols,
        )


def msort(inp):
    logger.debug("GEMS MSORT")
    if inp.is_complex():
        raise RuntimeError('"msort" not implemented for complex dtypes')
    out = torch.empty_like(inp, memory_format=torch.preserve_format)
    msort_out(inp, out=out)
    return out


def msort_out(inp, *, out):
    logger.debug("GEMS MSORT.OUT")
    if inp.is_complex():
        raise RuntimeError('"msort" not implemented for complex dtypes')
    if out.dtype != inp.dtype:
        raise RuntimeError(
            f"Expected out tensor to have dtype {inp.dtype}, but got {out.dtype} instead"
        )
    if out.device != inp.device:
        raise RuntimeError(
            f"Expected out tensor to have device {inp.device}, but got {out.device} instead"
        )
    if (
        inp.numel()
        and inp.untyped_storage().data_ptr() == out.untyped_storage().data_ptr()
    ):
        # Preserve all source values before resize or any cross-program stores.
        source = torch.empty(inp.shape, dtype=inp.dtype, device=inp.device)
        copy_(source, inp)
        inp = source
    if out.shape != inp.shape:
        out.resize_(inp.shape)

    if inp.is_contiguous() and out.is_contiguous():
        _msort_contiguous(inp, out)
    else:
        contiguous_inp = contiguous(inp)
        contiguous_out = torch.empty_like(contiguous_inp)
        _msort_contiguous(contiguous_inp, contiguous_out)
        copy_(out, contiguous_out)
    return out
