# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry
from flag_gems.utils.limits import get_dtype_min

logger = logging.getLogger(__name__)

# The quantized integer dtypes ``aten::quantized_max_pool2d`` dispatches over
# (its kernel body is wrapped in ``AT_DISPATCH_QINT_TYPES_AND(Byte, ...)``),
# mapped to the dtype of their ``int_repr()``. Pooling runs directly on the
# integer representation, so the kernel only needs their width/signedness.
_QINT_DTYPES = {
    torch.quint8: torch.uint8,
    torch.qint8: torch.int8,
    torch.qint32: torch.int32,
}

# ATen reports the *C++* spelling of a dtype in the ``out=`` dtype error, e.g.
# "Expected out tensor to have dtype c10::quint8, but got c10::qint8 instead".
# Reproduce the spellings so the message matches the native operator verbatim.
_ATEN_DTYPE_NAMES = {
    torch.quint8: "c10::quint8",
    torch.qint8: "c10::qint8",
    torch.qint32: "c10::qint32",
    torch.float32: "float",
    torch.float64: "double",
    torch.float16: "c10::Half",
    torch.bfloat16: "c10::BFloat16",
    torch.bool: "bool",
    torch.uint8: "unsigned char",
    torch.int8: "signed char",
    torch.int16: "short int",
    torch.int32: "int",
    torch.int64: "long int",
    torch.complex64: "c10::complex<float>",
    torch.complex128: "c10::complex<double>",
}


def _aten_dtype_name(dtype: torch.dtype) -> str:
    return _ATEN_DTYPE_NAMES.get(dtype, str(dtype))


def max_pool2d_output_size(
    in_size: int,
    kernel_size: int,
    stride: int,
    padding: int,
    dilation: int,
    ceil_mode: bool = False,
) -> int:
    """Compute one spatial dimension of the 2-D max-pool output.

    Mirrors ``at::native::pooling_output_shape``, including the two checks it
    performs before computing the size and the ``ceil_mode`` correction that
    keeps the last pooling window starting inside the image.
    """
    if stride == 0:
        raise RuntimeError("stride should not be zero")
    if padding < 0:
        raise RuntimeError(f"pad must be non-negative, but got pad: {padding}")

    effective_kernel_size = (kernel_size - 1) * dilation + 1
    numerator = in_size + 2 * padding - effective_kernel_size
    if ceil_mode:
        # Python's floor division matches ATen's ``div_rtn`` for negatives too.
        output_size = (numerator + stride - 1) // stride + 1
        # PyTorch-compatible adjustment for ceil_mode: ensure that the last
        # pooling window starts inside the image.
        if (output_size - 1) * stride >= in_size + padding:
            output_size -= 1
    else:
        output_size = numerator // stride + 1

    return output_size


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("quantized_max_pool2d"),
    key=["out_h", "out_w", "kernel_h", "kernel_w", "stride_h", "stride_w"],
)
@triton.jit
def quantized_max_pool2d_kernel(
    input_ptr,
    output_ptr,
    # Input tensor strides
    in_stride_n,
    in_stride_c,
    in_stride_h,
    in_stride_w,
    # Output tensor strides
    out_stride_n,
    out_stride_c,
    out_stride_h,
    out_stride_w,
    # Input/Output shapes
    in_c,
    in_h,
    in_w,
    out_h,
    out_w,
    # Pooling parameters
    kernel_h: tl.constexpr,
    kernel_w: tl.constexpr,
    stride_h: tl.constexpr,
    stride_w: tl.constexpr,
    padding_h: tl.constexpr,
    padding_w: tl.constexpr,
    dilation_h: tl.constexpr,
    dilation_w: tl.constexpr,
    # Meta-parameters for tiling
    BLOCK_H: tl.constexpr,
    BLOCK_W: tl.constexpr,
):
    """Forward kernel for quantized 2-D max pooling.

    The kernel operates directly on the integer representation (``int_repr``) of
    a per-tensor quantized tensor -- ``uint8`` for ``quint8``, ``int8`` for
    ``qint8``, ``int32`` for ``qint32``. Because the quantization mapping
    ``real = (q - zero_point) * scale`` is monotonically increasing in ``q`` for
    a positive ``scale``, taking the max over the quantized integers is
    equivalent to taking the max over the real values. The identity of the max
    is what is stored, so no requantization is needed and the result is exact
    for every one of the three dtypes.

    Positions that fall outside the image are filled with the minimum of the
    *underlying integer* dtype, which is the same sentinel ATen's
    ``spatial_dilated_max_pooling`` uses
    (``std::numeric_limits<T::underlying>::lowest()``).

    Both sides are addressed through explicit strides, so a non-contiguous
    input needs no repacking and a channels-last output can be written in place.

    Grid: (N * C, cdiv(out_h, BLOCK_H) * cdiv(out_w, BLOCK_W))
    """
    pid_nc = tl.program_id(0)
    pid_hw = tl.program_id(1)
    num_w_blocks = tl.cdiv(out_w, BLOCK_W)
    h_block_idx = pid_hw // num_w_blocks
    w_block_idx = pid_hw % num_w_blocks
    n_idx = pid_nc // in_c
    c_idx = pid_nc % in_c

    h_out_offsets = h_block_idx * BLOCK_H + tl.arange(0, BLOCK_H)
    w_out_offsets = w_block_idx * BLOCK_W + tl.arange(0, BLOCK_W)

    dtype = input_ptr.type.element_ty
    min_val = get_dtype_min(dtype)
    max_val_acc = tl.full((BLOCK_H, BLOCK_W), min_val, dtype=dtype)

    input_base_ptr = input_ptr + n_idx * in_stride_n + c_idx * in_stride_c

    for kh in tl.static_range(0, kernel_h):
        for kw in tl.static_range(0, kernel_w):
            h_in = h_out_offsets[:, None] * stride_h - padding_h + kh * dilation_h
            w_in = w_out_offsets[None, :] * stride_w - padding_w + kw * dilation_w
            in_mask = (h_in >= 0) & (h_in < in_h) & (w_in >= 0) & (w_in < in_w)
            input_offset = h_in * in_stride_h + w_in * in_stride_w
            current_val = tl.load(
                input_base_ptr + input_offset, mask=in_mask, other=min_val
            )
            max_val_acc = tl.maximum(max_val_acc, current_val)

    out_base_ptr = output_ptr + n_idx * out_stride_n + c_idx * out_stride_c
    output_block_ptr = (
        out_base_ptr
        + h_out_offsets[:, None] * out_stride_h
        + w_out_offsets[None, :] * out_stride_w
    )

    out_mask = (h_out_offsets[:, None] < out_h) & (w_out_offsets[None, :] < out_w)
    tl.store(output_block_ptr, max_val_acc, mask=out_mask)


def _check_maxpool2d_params(kernel_size, stride, padding, dilation):
    """Mirror ATen's ``check_maxpool2d_params`` argument-shape validation.

    Returns the parameters expanded to 2-tuples. ``stride`` may be an empty
    sequence, in which case ``None`` is returned for it so the caller can
    substitute ``kernel_size`` (what ATen does right after this check).

    ATen accepts 1- *or* 2-element lists for kernel_size/padding/dilation, but
    then indexes ``[0]`` and ``[1]`` unconditionally, so a 1-element list reads
    past the end of the array. We reject that instead of reproducing the
    out-of-bounds read; a bare Python int reaches the ``int[2]`` schema slot
    broadcast to both dims, which is the well-defined way to say "same value".
    """

    def _length_checked(param, name, message):
        if isinstance(param, int):
            # A bare int reaches the ATen schema as ``int[2]``, i.e. broadcast.
            return param, param
        if isinstance(param, (list, tuple)):
            if len(param) != 2:
                raise RuntimeError(f"{message}{len(param)}")
            return tuple(int(p) for p in param)
        raise RuntimeError(f"Invalid {name}: {param}")

    kernel = _length_checked(
        kernel_size, "kernel_size", "Expected 1d or 2d kernel size, got "
    )

    if isinstance(stride, (list, tuple)) and len(stride) == 0:
        strides = None
    elif stride is None:
        # The schema default is ``int[2] stride=[]``; ``None`` from a Python
        # caller means the same thing as an omitted argument.
        strides = None
    else:
        # Note the missing space after "got": ATen's message really does read
        # "Expected no strides or 2d strides, got3".
        strides = _length_checked(
            stride, "stride", "Expected no strides or 2d strides, got"
        )

    pads = _length_checked(padding, "padding", "Expected 1d or 2d padding, got ")
    dilations = _length_checked(
        dilation, "dilation", "Expected 1d or 2d dilation, got "
    )

    if any(d < 1 for d in dilations):
        raise RuntimeError("Expected dilation >= 1")

    return kernel, strides, pads, dilations


def _parse_pool_params(kernel_size, stride, padding, dilation):
    """Parse and validate 2-D pooling parameters the way ATen does.

    Each parameter can be an int (applied to both spatial dims) or a 2-element
    tuple/list (H, W). An empty or omitted ``stride`` falls back to
    ``kernel_size``, matching the ``int[2] stride=[]`` schema default of
    ``aten::quantized_max_pool2d``.
    """
    kernel, strides, pads, dilations = _check_maxpool2d_params(
        kernel_size, stride, padding, dilation
    )
    if strides is None:
        strides = kernel

    kernel_h, kernel_w = kernel
    stride_h, stride_w = strides
    padding_h, padding_w = pads
    dilation_h, dilation_w = dilations

    # ATen validates kernel/stride positivity inside ``q_maxpool_2d``, in this
    # order, before it looks at the input tensor at all.
    if kernel_h <= 0 or kernel_w <= 0:
        raise RuntimeError("kernel_size should be greater than zero.")
    if stride_h <= 0 or stride_w <= 0:
        raise RuntimeError("strides should be greater than zero.")

    return (
        kernel_h,
        kernel_w,
        stride_h,
        stride_w,
        padding_h,
        padding_w,
        dilation_h,
        dilation_w,
    )


# Backwards-compatible alias: the benchmark and earlier revisions of this file
# import ``_parse_pool_params`` under this name.
_parse_param_pairs = _parse_pool_params


def _check_quantized_input(input):
    """Reject inputs ATen's ``quantized_max_pool2d`` cannot accept.

    ATen runs this *after* the parameter and shape checks: it only touches the
    quantizer when it reaches ``qx.q_scale()``, so a per-channel input with a
    bad kernel size reports the kernel size, not the qscheme. Keep the same
    order by calling this last.
    """
    if not input.is_quantized:
        raise RuntimeError(
            "quantized_max_pool2d expects a quantized tensor "
            "(torch.quint8, torch.qint8 or torch.qint32)"
        )
    if input.qscheme() != torch.per_tensor_affine:
        # ATen's TORCH_CHECK inside the quantizer, verbatim (the trailing
        # boilerplate about improving the message is appended by TORCH_CHECK
        # itself and is not reproduced here).
        raise RuntimeError(
            "Expected quantizer->qscheme() == kPerTensorAffine to be true, "
            "but got false."
        )
    if input.dtype not in _QINT_DTYPES:
        raise RuntimeError(
            f"quantized_max_pool2d not implemented for '{input.dtype}'; "
            "expected one of torch.quint8, torch.qint8, torch.qint32"
        )


def _quantized_max_pool2d_output_shape(input, params, ceil_mode):
    """Validate the input against ``params`` and return the output shape.

    Reproduces the remaining checks of ATen's ``q_maxpool_2d``, in order: rank
    (3 or 4), non-zero C/H/W, padding vs. half the kernel, and finally a
    positive output size. A 3-D input is the native (C, H, W) form -- ATen
    treats it as a single batch.
    """
    (
        kernel_h,
        kernel_w,
        stride_h,
        stride_w,
        padding_h,
        padding_w,
        dilation_h,
        dilation_w,
    ) = params

    ndim = input.dim()
    if ndim not in (3, 4):
        raise RuntimeError("Expecting the input tensor of rank 3 or 4.")

    in_n = input.shape[0] if ndim == 4 else 1
    in_c, in_h, in_w = input.shape[-3:]
    # ATen only requires C/H/W to be non-zero; an empty batch is legal.
    if in_c <= 0 or in_h <= 0 or in_w <= 0:
        raise RuntimeError("input dimensions must be non-zero.")
    if kernel_h // 2 < padding_h or kernel_w // 2 < padding_w:
        raise RuntimeError("padding should be smaller than half of kernel_size.")

    out_h = max_pool2d_output_size(
        in_h, kernel_h, stride_h, padding_h, dilation_h, ceil_mode
    )
    out_w = max_pool2d_output_size(
        in_w, kernel_w, stride_w, padding_w, dilation_w, ceil_mode
    )
    if out_h <= 0 or out_w <= 0:
        raise RuntimeError(
            f"Given input size: ({in_c}x{in_h}x{in_w}). "
            f"Calculated output size: ({in_c}x{out_h}x{out_w}). "
            "Output size is too small."
        )

    if ndim == 3:
        return (in_c, out_h, out_w)
    return (in_n, in_c, out_h, out_w)


def _int_view(qtensor):
    """Alias a quantized tensor's storage as a writable integer tensor.

    ``int_repr()`` returns a *copy*, so it cannot be used as a kernel
    destination, and for a strided input it would materialise a compacted copy.
    Aliasing the storage with the tensor's own sizes and strides gives a view
    the kernel can read from or store into, whatever layout it has.
    """
    return torch.empty(
        0, dtype=_QINT_DTYPES[qtensor.dtype], device=qtensor.device
    ).set_(
        qtensor.untyped_storage(),
        qtensor.storage_offset(),
        tuple(qtensor.shape),
        qtensor.stride(),
    )


def _as_4d(int_tensor):
    """View a 3-D (C, H, W) integer tensor as (1, C, H, W)."""
    if int_tensor.dim() == 3:
        return int_tensor.unsqueeze(0)
    return int_tensor


def _launch_quantized_max_pool2d(input_int, out_int, params):
    """Run the pooling kernel over an integer view of the input."""
    (
        kernel_h,
        kernel_w,
        stride_h,
        stride_w,
        padding_h,
        padding_w,
        dilation_h,
        dilation_w,
    ) = params

    input_int = _as_4d(input_int)
    out_int = _as_4d(out_int)
    in_n, in_c, in_h, in_w = input_int.shape
    _, _, out_h, out_w = out_int.shape

    grid = lambda meta: (
        in_n * in_c,
        triton.cdiv(out_h, meta["BLOCK_H"]) * triton.cdiv(out_w, meta["BLOCK_W"]),
    )

    quantized_max_pool2d_kernel[grid](
        input_int,
        out_int,
        *input_int.stride(),
        *out_int.stride(),
        in_c,
        in_h,
        in_w,
        out_h,
        out_w,
        kernel_h,
        kernel_w,
        stride_h,
        stride_w,
        padding_h,
        padding_w,
        dilation_h,
        dilation_w,
    )
    return out_int


def _output_memory_format(input):
    """Pick the memory format the native kernel for this device allocates with.

    The kernel this operator replaces is ``quantized_max_pool2d_cudnn``, not the
    CPU one, and the two disagree. cuDNN has no strided or 3-D convolution path,
    so its wrapper in ``QuantizedMaxPool2d.cpp`` permutes *every* 4-D input to
    channels-last first -- NCHW, strided and already-channels-last alike -- and
    always allocates the result with ``memory_format=ChannelsLast``. A 3-D
    (C, H, W) input is instead viewed as a single batch and stays
    NCHW-contiguous.

    The CPU kernel only produces a channels-last result when the input already
    has that layout, and gives an NCHW-contiguous result otherwise (including
    for a degenerate ``C == 1`` shape, where a channels-last allocation would
    have different strides). That rule is kept for a CPU input, so a direct call
    with CPU tensors stays layout-identical to the CPU operator.

    The rule keys on the device rather than the dtype: ``quantized_max_pool2d``
    is registered for the QuantizedCUDA dispatch key, where a 4-D input always
    reaches the cuDNN path, and cuDNN only handles ``qint8``. For
    ``quint8``/``qint32`` the native CUDA op raises
    ("TensorDescriptor does not support ..."), so there is no native layout to
    contradict, and giving every 4-D accelerator input the same channels-last
    layout avoids a result whose strides depend on the dtype.
    """
    if input.dim() != 4:
        return torch.contiguous_format
    if input.device.type != "cpu":
        return torch.channels_last
    if (
        input.is_contiguous(memory_format=torch.channels_last)
        and not input.is_contiguous()
    ):
        return torch.channels_last
    return torch.contiguous_format


def quantized_max_pool2d(
    input: torch.Tensor,
    kernel_size,
    stride=(),
    padding=0,
    dilation=1,
    ceil_mode=False,
):
    """Apply 2-D max pooling to a per-tensor quantized tensor.

    Accepts both native input forms -- 4-D (N, C, H, W) and 3-D (C, H, W) --
    and the three dtypes the native operator dispatches over:
    ``torch.quint8``, ``torch.qint8`` and ``torch.qint32``. Pooling is
    performed directly over the quantized integer representation, which (for a
    positive scale) yields the same result as pooling over the dequantized
    values while keeping the input's ``scale``/``zero_point`` on the output.

    An omitted or empty ``stride`` falls back to ``kernel_size``, matching the
    ``int[2] stride=[]`` schema default of ``aten::quantized_max_pool2d``.
    """
    logger.debug("GEMS QUANTIZED_MAX_POOL2D")

    params = _parse_pool_params(kernel_size, stride, padding, dilation)
    out_shape = _quantized_max_pool2d_output_shape(input, params, ceil_mode)
    _check_quantized_input(input)

    scale = float(input.q_scale())
    zero_point = int(input.q_zero_point())

    # Allocate the quantized result directly: ``_empty_affine_quantized``
    # honours ``memory_format``, whereas wrapping a strided integer tensor with
    # ``_make_per_tensor_quantized_tensor`` silently normalises its strides on
    # CUDA and would drop the channels-last layout.
    out = torch._empty_affine_quantized(
        out_shape,
        scale=scale,
        zero_point=zero_point,
        dtype=input.dtype,
        device=input.device,
        memory_format=_output_memory_format(input),
    )

    if out.numel() != 0:
        _launch_quantized_max_pool2d(_int_view(input), _int_view(out), params)

    return out


def _contiguous_strides(shape):
    strides = []
    acc = 1
    for size in reversed(shape):
        strides.append(acc)
        acc *= size
    return tuple(reversed(strides)), acc


def _resize_quantized_out(out, shape):
    """Resize a quantized ``out`` tensor to ``shape``, ATen-style.

    ``aten::resize_`` and ``aten::set_.source_Tensor`` are both unimplemented
    for the QuantizedCUDA backend, so the metadata is rewritten through
    ``set_(storage, offset, size, stride)``, which is registered. This
    reproduces what ``at::native::resize_output`` does for a strided tensor:
    the storage offset is preserved, the storage only ever grows, and the
    resized tensor is given contiguous strides.
    """
    strides, numel = _contiguous_strides(tuple(shape))

    storage = out.untyped_storage()
    offset = out.storage_offset()
    needed = (offset + numel) * out.element_size()
    if numel != 0 and storage.size() < needed:
        storage.resize_(needed)
    out.set_(storage, offset, tuple(shape), strides)
    return out


def _aliases(input, out):
    """True when ``out`` may share storage with ``input``."""
    return out.untyped_storage().data_ptr() == input.untyped_storage().data_ptr()


def _same_quantizer(input, out):
    """True when ``out`` already carries ``input``'s per-tensor quantizer.

    A kernel write moves integers only, so it cannot re-point ``out``'s
    quantizer the way ``copy_`` does; pooling in place is only equivalent when
    ``out`` is per-tensor affine with the same ``scale`` and ``zero_point``.
    """
    return (
        out.qscheme() == torch.per_tensor_affine
        and out.q_scale() == input.q_scale()
        and out.q_zero_point() == input.q_zero_point()
    )


def _adopt_quantizer(out, source):
    """Re-point ``out`` at ``source``'s per-tensor quantizer, in place.

    ``out.copy_(source)`` is the only ATen operation that moves a quantizer
    between quantized tensors, but it moves the values too. Since the values
    are written by the kernel (or copied separately through ``_copy_int``),
    only the quantizer needs to move, and that can be done with ``.data``:
    assigning an alias that shares ``out``'s storage, offset, sizes and strides
    swaps the quantizer while leaving the tensor's storage, layout and identity
    untouched -- the caller's ``out`` object is mutated in place, and a strided
    or offset view keeps writing into its own slice of the buffer.

    The alias is built with ``_empty_affine_quantized`` + ``set_`` because
    ``_make_per_tensor_quantized_tensor`` (and ``Tensor.to``) silently
    normalises the strides of a quantized tensor on CUDA, which would lose a
    channels-last layout.
    """
    alias = torch._empty_affine_quantized(
        0,
        scale=float(source.q_scale()),
        zero_point=int(source.q_zero_point()),
        dtype=out.dtype,
        device=out.device,
    )
    alias.set_(
        out.untyped_storage(),
        out.storage_offset(),
        tuple(out.shape),
        out.stride(),
    )
    out.data = alias
    return out


def _copy_int(dst_int, src_int):
    """Copy integers device-side, honouring both sides' strides.

    ``dst_int`` / ``src_int`` are the integer views produced by ``_int_view``,
    so the tensors are plain integer tensors and reach FlagGems' Triton
    ``copy_`` instead of being redispatched to ATen the way a quantized
    ``Tensor.copy_`` is.
    """
    from flag_gems.ops.copy import copy_

    copy_(dst_int, src_int)
    return dst_int


def quantized_max_pool2d_out(
    input: torch.Tensor,
    kernel_size,
    stride=(),
    padding=0,
    dilation=1,
    ceil_mode=False,
    *,
    out: torch.Tensor,
):
    """``out`` variant of :func:`quantized_max_pool2d`.

    Follows the contract of the autogenerated ``quantized_max_pool2d.out``
    kernel, which is written in terms of the functional one:

    .. code-block:: cpp

        auto tmp_output = at::quantized_max_pool2d(self, ...);
        resize_out_helper(out, tmp_output);   // resize_output(out, tmp.sizes())
        copy_arg(out, tmp_output);            // dtype check, device check, copy_

    So the shape, dtype and device contract matches ATen's: the result is
    computed *first* (which is also what makes an ``out`` that aliases the input
    safe), then ``out`` is resized to the result's shape, then its dtype and
    device are checked, and finally the values are written through ``out``'s own
    strides and the input's ``scale`` / ``zero_point`` are carried over. A
    mismatched-dtype ``out`` is therefore still resized before the error
    surfaces, exactly as in ATen.

    The final write differs from ATen in *how*, not in what lands where: the
    pooling kernel is strided on both sides, so when ``out`` does not overlap
    the input it stores the pooled integers through ``out`` directly, and only
    the quantizer is re-pointed (:func:`_adopt_quantizer`, no ``copy_`` at
    all). The aliasing case -- where ``out`` must keep the input's values until
    the result is complete -- copies the integer representations device-side
    through FlagGems' Triton ``copy_`` (:func:`_copy_int`). Neither path calls
    the native quantized ``copy_``: ``Tensor.copy_`` on quantized tensors
    redispatches to ATen, which would add a native O(n) pass after the kernel.
    """
    logger.debug("GEMS QUANTIZED_MAX_POOL2D_OUT")

    # The functional result's shape, dtype and device are all known without
    # running the kernel, so the resize and the two checks happen in ATen's
    # order either way; computing first is only *required* when ``out`` aliases
    # the input, where the resize would otherwise reshape the input out from
    # under the pooling.
    params = _parse_pool_params(kernel_size, stride, padding, dilation)
    out_shape = _quantized_max_pool2d_output_shape(input, params, ceil_mode)
    _check_quantized_input(input)

    result = None
    if _aliases(input, out):
        result = quantized_max_pool2d(
            input, kernel_size, stride, padding, dilation, ceil_mode
        )

    if tuple(out.shape) != tuple(out_shape):
        _resize_quantized_out(out, out_shape)

    if out.dtype != input.dtype:
        raise RuntimeError(
            f"Expected out tensor to have dtype {_aten_dtype_name(input.dtype)}, "
            f"but got {_aten_dtype_name(out.dtype)} instead"
        )
    if out.device != input.device:
        raise RuntimeError(
            f"Expected out tensor to have device {input.device}, "
            f"but got {out.device} instead"
        )

    if out.qscheme() != torch.per_tensor_affine:
        # ATen's quantized ``copy_`` rejects a per-channel destination with this
        # message. It is raised by the copy, which runs after the resize and the
        # dtype/device checks, so it comes last here too.
        raise RuntimeError("Quantized Copy only works with same qscheme")

    if result is None:
        # ``out`` cannot overlap the input, so the pooled integers can be
        # written straight through ``out``'s own strides and storage offset --
        # the kernel is strided on both sides, so an ``out`` in any layout,
        # including a non-contiguous view, receives exactly the elements
        # ``out.copy_(functional_result)`` would have placed. Only the
        # quantizer still has to move, which :func:`_adopt_quantizer` does
        # without a copy.
        if out.numel() != 0:
            _launch_quantized_max_pool2d(_int_view(input), _int_view(out), params)
        if _same_quantizer(input, out):
            return out
        return _adopt_quantizer(out, input)

    # ``out`` aliases the input, so pooling cannot write into it directly: the
    # functional result was computed into ``result`` first. Moving those
    # integers into ``out`` is the one case that genuinely needs a copy; it is
    # done over the integer views, which lands in FlagGems' Triton ``copy_``.
    # A quantized ``out.copy_(result)`` would redispatch to ATen and run an
    # extra native O(n) pass after the Triton kernel had already run.
    if out.numel() != 0:
        _copy_int(_int_view(out), _int_view(result))
    return _adopt_quantizer(out, result)
