# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


# ``aten::row_indices`` is a sparse-tensor *accessor* exposing the stored COO
# row indices of a CSC/BSC tensor. The stored buffer is shared by the layout,
# so the native operator returns an aliasing view: two calls return tensors
# backed by the same storage, and mutating the result mutates the sparse
# tensor's indices (verified against ``torch.Tensor.row_indices`` on both CPU
# and CUDA). ``row_indices_copy`` is the copying variant.
#
# There is no per-element computation to do here: the answer is always "the
# buffer the sparse layout already stores". Recreating that buffer in Triton
# would both cost a full copy on every access and, worse, break the aliasing
# contract (a fresh tensor would go stale when the layout's indices change).
# This implementation therefore returns the native accessor's aliasing view,
# reached through the public dispatcher below the autograd key -- no private
# ``torch._C`` dispatch APIs, no hard-coded CUDA keys, and no kernel capture.
# The backend kernel also supplies the layout validation and its exact
# messages (verified: ATen accepts CSC and BSC, and raises for BSR/CSR).
def row_indices(self: torch.Tensor) -> torch.Tensor:
    """Return the row indices of a sparse column-compressed (CSC/BSC) tensor.

    The result aliases the tensor's stored row-indices buffer, matching
    ``aten::row_indices``. Batched CSC/BSC layouts keep their full batch shape,
    exactly as the native reader reports them.
    """
    logger.debug("GEMS ROW_INDICES")

    # Dispatch below autograd: the backend (SparseCsrCUDA/SparseCsrCPU) kernel
    # reads the stored buffer and returns the aliasing view. Re-entering this
    # override would only recurse; the backend kernel is the single reader.
    with torch._C._AutoDispatchBelowAutograd():
        return torch.ops.aten.row_indices.default(self)
