# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext
from flag_gems.utils.shape_utils import MemOverlap, has_internal_overlapping

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("vstack"),
    key=[
        "max_tile_elems",
    ],
)
@triton.jit
def row_stack_kernel(
    itensor_ptr0,
    itensor_ptr1,
    itensor_ptr2,
    itensor_ptr3,
    output_ptr,
    local_row0,
    local_row1,
    local_row2,
    local_row3,
    exc_row_offset0,
    exc_row_offset1,
    exc_row_offset2,
    exc_row_offset3,
    total_row_offset,
    row_stride,
    max_tile_elems,
    BLOCK_SIZE: tl.constexpr,
):
    pid_x = ext.program_id(axis=0)
    tensor_idx = ext.program_id(axis=1)
    col_idx = tl.arange(0, BLOCK_SIZE)

    intensor_ptr = tl.where(tensor_idx == 0, itensor_ptr0, itensor_ptr1)
    intensor_ptr = tl.where(tensor_idx == 2, itensor_ptr2, intensor_ptr)
    intensor_ptr = tl.where(tensor_idx == 3, itensor_ptr3, intensor_ptr)
    base_exc_row_idx = tl.where(tensor_idx == 0, exc_row_offset0, exc_row_offset1)
    base_exc_row_idx = tl.where(tensor_idx == 2, exc_row_offset2, base_exc_row_idx)
    base_exc_row_idx = tl.where(tensor_idx == 3, exc_row_offset3, base_exc_row_idx)
    local_row = tl.where(tensor_idx == 0, local_row0, local_row1)
    local_row = tl.where(tensor_idx == 2, local_row2, local_row)
    local_row = tl.where(tensor_idx == 3, local_row3, local_row)

    # Widen through the tensor operands rather than through ``row_stride``:
    # Triton specializes a scalar ``1`` (and ``0``) to a constexpr, which has no
    # ``.to`` method, so casting the scalar itself would fail for width-1 rows.
    end_idx = local_row.to(tl.int64) * row_stride
    idx = (pid_x * BLOCK_SIZE + col_idx).to(tl.int64)
    offset_mask = idx < end_idx
    in_offset = intensor_ptr + idx
    row_stride_offset = (total_row_offset + base_exc_row_idx).to(tl.int64) * row_stride
    out_offset = output_ptr + row_stride_offset + idx
    out = tl.load(in_offset, mask=offset_mask)
    tl.store(out_offset, out, mask=offset_mask)


def _row_width(shape):
    """Number of elements in one row = product of the trailing dimensions."""
    width = 1
    for size in shape[1:]:
        width *= size
    return width


def _row_strides(shape):
    """Row-major contiguous strides, matching ATen for zero-sized dimensions.

    ATen skips the stride multiply for a zero-sized dimension, so ``(5, 0)``
    gets stride ``(1, 1)`` rather than ``(0, 1)``.  Reproducing that keeps the
    output metadata identical to the reference for empty inputs.
    """
    strides = [0] * len(shape)
    step = 1
    for dim in range(len(shape) - 1, -1, -1):
        strides[dim] = step
        if shape[dim] != 0:
            step *= shape[dim]
    return strides


def _channels_last_strides(shape):
    """channels_last (rank 4) / channels_last_3d (rank 5) strides."""
    if len(shape) == 4:
        _, c, h, w = shape
        return [c * h * w, 1, w * c, c]
    _, c, d, h, w = shape
    return [c * d * h * w, 1, h * w * c, w * c, c]


def _strides_for(shape, memory_format):
    """Strides ATen's allocator uses for ``shape`` in ``memory_format``.

    For channels-last the allocated strides are what the kernel needs: dim 0 is
    stepped by ``row_width`` (the product of the trailing sizes) and each row is
    a dense run of ``row_width`` elements, tiled back to back.
    """
    if memory_format == torch.channels_last and len(shape) == 4:
        return _channels_last_strides(shape)
    if memory_format == torch.channels_last_3d and len(shape) == 5:
        return _channels_last_strides(shape)
    return _row_strides(shape)


def _promote_dtype(tensors):
    dtype = tensors[0].dtype
    for tensor in tensors[1:]:
        if tensor.dtype != dtype:
            dtype = torch.promote_types(dtype, tensor.dtype)
    return dtype


def _suggest_memory_format(tensor):
    """Mirror ATen's ``TensorImpl::suggest_memory_format``.

    Only an exact channels-last / channels-last-3d layout (rank 4 / rank 5) is
    reported; anything else maps to the default contiguous format.
    """
    from torch._prims_common import suggest_memory_format

    if tensor.layout != torch.strided:
        return torch.contiguous_format
    return suggest_memory_format(tensor)


def _derive_memory_format(tensors):
    """ATen's ``cat_compute_output_memory_format``: all inputs must agree."""
    fmt = None
    for tensor in tensors:
        current = _suggest_memory_format(tensor)
        if current == torch.contiguous_format:
            return torch.contiguous_format
        if fmt is not None and fmt != current:
            return torch.contiguous_format
        fmt = current
    return fmt if fmt is not None else torch.contiguous_format


def _allocate(shape, strides, dtype, device):
    return torch.empty_strided(tuple(shape), tuple(strides), dtype=dtype, device=device)


def _normalize_tensors(tensors):
    """``atleast_2d`` plus ATen-compatible validation."""
    tensors = list(torch.atleast_2d(tensors))
    if len(tensors) == 0:
        raise RuntimeError("vstack expects a non-empty TensorList")

    device = tensors[0].device
    ndim = tensors[0].dim()
    for i, tensor in enumerate(tensors[1:], start=1):
        if tensor.device != device:
            raise RuntimeError(
                "Expected all tensors to be on the same device, but got "
                f"{tensor.device} and {device}"
            )
        if tensor.dim() != ndim:
            raise RuntimeError(
                "Tensors must have same number of dimensions: got "
                f"{ndim} and {tensor.dim()}"
            )
        for dim, (expected, got) in enumerate(zip(tensors[0].shape, tensor.shape)):
            if dim != 0 and expected != got:
                raise RuntimeError(
                    "Sizes of tensors must match except in dimension 0. "
                    f"Expected size {expected} but got size {got} for tensor "
                    f"number {i} in the list."
                )
    return tensors


def _cast_tensors(tensors, dtype, memory_format):
    """Bring every input to ``dtype`` with a row block dense in layout order.

    The kernel copies row blocks positionally, so each input must be dense in
    the *same* trailing layout as the output; a channels-last input that was
    flattened to contiguous order would scatter elements to wrong positions.
    """
    cast = []
    for tensor in tensors:
        if tensor.dtype != dtype:
            tensor = tensor.to(dtype)
        if not tensor.is_contiguous(memory_format=memory_format):
            tensor = tensor.contiguous(memory_format=memory_format)
        cast.append(tensor)
    return cast


def _run_kernel(tensors, output, row_width, out_row_stride):
    """Copy every input row block into ``output`` through the Triton kernel."""
    num_tensors = len(tensors)
    outer_iters = triton.cdiv(num_tensors, 4)
    total_row_offset = 0
    for i in range(outer_iters):
        max_rows = 1
        itensors = []
        exclusive_row = []
        local_row = []
        array_row_offset = 0
        scheduled_num_tensors = 0
        for j in range(4):
            tensor_idx = i * 4 + j
            if tensor_idx < num_tensors:
                scheduled_num_tensors += 1
                tensor = tensors[tensor_idx]
                itensors.append(tensor)
                local_row.append(tensor.shape[0])
                exclusive_row.append(array_row_offset)
                array_row_offset += tensor.shape[0]
                max_rows = max(max_rows, tensor.shape[0])
            else:
                empty_tensor = torch.empty(
                    0, dtype=tensors[0].dtype, device=tensors[0].device
                )
                itensors.append(empty_tensor)
                local_row.append(local_row[-1])
                exclusive_row.append(exclusive_row[-1])
        max_tile_elems = max_rows * row_width
        grid = lambda META: (
            triton.cdiv(max_tile_elems, META["BLOCK_SIZE"]),
            scheduled_num_tensors,
        )
        # Launch the kernel
        with torch_device_fn.device(tensors[0].device):
            row_stack_kernel[grid](
                itensors[0],
                itensors[1],
                itensors[2],
                itensors[3],
                output,
                local_row[0],
                local_row[1],
                local_row[2],
                local_row[3],
                exclusive_row[0],
                exclusive_row[1],
                exclusive_row[2],
                exclusive_row[3],
                total_row_offset,
                out_row_stride,
                max_tile_elems,
            )
            total_row_offset += array_row_offset
    return output


def _output_shape(tensors):
    total_rows = sum(tensor.shape[0] for tensor in tensors)
    shape = list(tensors[0].shape)
    shape[0] = total_rows
    return shape


def _prepare(tensors):
    """Shared validation/shape work for both entry points."""
    tensors = _normalize_tensors(tensors)
    memory_format = _derive_memory_format(tensors)
    dtype = _promote_dtype(tensors)
    # A zero-sized trailing dimension means zero work: ``stride(0)`` can still
    # be non-zero for such inputs (e.g. ``(3, 0)`` has stride ``(1, 1)``), so a
    # launch based on ``rows * stride(0)`` would run out of bounds.
    row_width = _row_width(tensors[0].shape)
    output_shape = _output_shape(tensors)
    return tensors, memory_format, dtype, row_width, output_shape


def row_stack(tensors: list):
    logger.debug("GEMS ROW_STACK")

    tensors, memory_format, dtype, row_width, output_shape = _prepare(tensors)
    device = tensors[0].device
    if row_width == 0 or output_shape[0] == 0:
        # Nothing to copy; still hand back a correctly shaped, format-correct
        # tensor rather than launching a kernel that would read out of bounds.
        return _allocate(
            output_shape, _strides_for(output_shape, memory_format), dtype, device
        )

    strides = _strides_for(output_shape, memory_format)
    output = _allocate(output_shape, strides, dtype, device)
    c_tensors = _cast_tensors(tensors, dtype, memory_format)
    return _run_kernel(c_tensors, output, row_width, strides[0])


def _check_out(out, output_shape, dtype, memory_format, tensors):
    """Validate/prepare ``out`` the way ATen's ``cat_out`` meta function does.

    The ordering mirrors ATen: the castability check runs before the output is
    resized, and the overlap checks run afterwards.
    """
    if not torch.can_cast(dtype, out.dtype):
        raise TypeError(
            "torch.cat(): input types can't be cast to the desired output type "
            f"{out.dtype}"
        )

    if list(out.shape) != list(output_shape):
        out.resize_(output_shape)
        # ``resize_`` always installs contiguous strides, whereas ATen's
        # ``set_output_raw_strided`` re-imposes the derived memory format; for
        # channels-last that changes the strides, so restore them here.
        strides = _strides_for(list(out.shape), memory_format)
        if tuple(out.stride()) != tuple(strides):
            out.as_strided_(tuple(out.shape), tuple(strides))

    if has_internal_overlapping(out) == MemOverlap.Yes:
        raise RuntimeError(
            "unsupported operation: more than one element of the written-to "
            "tensor refers to a single memory location. Please clone() the "
            "tensor before performing the operation."
        )
    for tensor in tensors:
        if torch._C._overlaps(out, tensor):
            raise RuntimeError(
                "unsupported operation: some elements of the input tensor and "
                "the written-to tensor refer to a single memory location. "
                "Please clone() the tensor before performing the operation."
            )
    return out


def row_stack_out(tensors: list, *, out: torch.Tensor):
    logger.debug("GEMS ROW_STACK_OUT")

    tensors, memory_format, dtype, row_width, output_shape = _prepare(tensors)
    _check_out(out, output_shape, dtype, memory_format, tensors)

    if row_width == 0 or output_shape[0] == 0:
        return out

    c_tensors = _cast_tensors(tensors, dtype, memory_format)

    # Fast path: ``out`` stores rows as dense runs of ``row_width`` elements and
    # its trailing strides match the layout the kernel assumes.  This holds for
    # contiguous and for channels-last outputs, so only an arbitrary strided
    # view falls through to the staging copy below.
    fast = out.dtype == dtype and tuple(out.stride()) == tuple(
        _strides_for(list(out.shape), memory_format)
    )
    if fast:
        return _run_kernel(c_tensors, out, row_width, out.stride(0))

    # Otherwise scatter through a dense staging buffer; ``copy_`` is
    # stride-aware and also honours ``out``'s dtype.
    strides = _strides_for(output_shape, memory_format)
    staging = _allocate(output_shape, strides, dtype, out.device)
    _run_kernel(c_tensors, staging, row_width, strides[0])
    out.copy_(staging)
    return out
