# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _lstm_cell_backward_kernel(
    grad_hy,
    grad_cy,
    input_gates,
    hidden_gates,
    input_bias,
    hidden_bias,
    cx,
    cy,
    grad_gates,
    grad_cx,
    batch_size,
    hidden_size,
    grad_hy_stride_0,
    grad_hy_stride_1,
    grad_cy_stride_0,
    grad_cy_stride_1,
    input_gates_stride_0,
    input_gates_stride_1,
    hidden_gates_stride_0,
    hidden_gates_stride_1,
    input_bias_stride,
    hidden_bias_stride,
    cx_stride_0,
    cx_stride_1,
    cy_stride_0,
    cy_stride_1,
    BLOCK_SIZE: tl.constexpr,
    HAS_GRAD_HY: tl.constexpr,
    HAS_GRAD_CY: tl.constexpr,
    HAS_INPUT_BIAS: tl.constexpr,
    HAS_HIDDEN_BIAS: tl.constexpr,
    IS_FP64: tl.constexpr,
    IS_FP16: tl.constexpr,
    IS_BF16: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    n_elements = batch_size * hidden_size
    mask = offsets < n_elements
    rows = offsets // hidden_size
    cols = offsets % hidden_size

    input_offsets = rows * input_gates_stride_0 + cols * input_gates_stride_1
    hidden_offsets = rows * hidden_gates_stride_0 + cols * hidden_gates_stride_1

    gate_i = tl.load(input_gates + input_offsets, mask=mask, other=0.0)
    gate_f = tl.load(
        input_gates + input_offsets + hidden_size * input_gates_stride_1,
        mask=mask,
        other=0.0,
    )
    gate_c = tl.load(
        input_gates + input_offsets + 2 * hidden_size * input_gates_stride_1,
        mask=mask,
        other=0.0,
    )
    gate_o = tl.load(
        input_gates + input_offsets + 3 * hidden_size * input_gates_stride_1,
        mask=mask,
        other=0.0,
    )
    gate_i += tl.load(hidden_gates + hidden_offsets, mask=mask, other=0.0)
    gate_f += tl.load(
        hidden_gates + hidden_offsets + hidden_size * hidden_gates_stride_1,
        mask=mask,
        other=0.0,
    )
    gate_c += tl.load(
        hidden_gates + hidden_offsets + 2 * hidden_size * hidden_gates_stride_1,
        mask=mask,
        other=0.0,
    )
    gate_o += tl.load(
        hidden_gates + hidden_offsets + 3 * hidden_size * hidden_gates_stride_1,
        mask=mask,
        other=0.0,
    )

    # ATen materializes every tensor addition in the input dtype. Preserve
    # those rounding boundaries before applying an optional bias.
    if IS_FP16:
        gate_i = gate_i.to(tl.float16)
        gate_f = gate_f.to(tl.float16)
        gate_c = gate_c.to(tl.float16)
        gate_o = gate_o.to(tl.float16)
    if IS_BF16:
        gate_i = gate_i.to(tl.bfloat16)
        gate_f = gate_f.to(tl.bfloat16)
        gate_c = gate_c.to(tl.bfloat16)
        gate_o = gate_o.to(tl.bfloat16)

    if HAS_INPUT_BIAS:
        gate_i += tl.load(input_bias + cols * input_bias_stride, mask=mask, other=0.0)
        gate_f += tl.load(
            input_bias + (hidden_size + cols) * input_bias_stride,
            mask=mask,
            other=0.0,
        )
        gate_c += tl.load(
            input_bias + (2 * hidden_size + cols) * input_bias_stride,
            mask=mask,
            other=0.0,
        )
        gate_o += tl.load(
            input_bias + (3 * hidden_size + cols) * input_bias_stride,
            mask=mask,
            other=0.0,
        )
        if IS_FP16:
            gate_i = gate_i.to(tl.float16)
            gate_f = gate_f.to(tl.float16)
            gate_c = gate_c.to(tl.float16)
            gate_o = gate_o.to(tl.float16)
        if IS_BF16:
            gate_i = gate_i.to(tl.bfloat16)
            gate_f = gate_f.to(tl.bfloat16)
            gate_c = gate_c.to(tl.bfloat16)
            gate_o = gate_o.to(tl.bfloat16)

    if HAS_HIDDEN_BIAS:
        gate_i += tl.load(hidden_bias + cols * hidden_bias_stride, mask=mask, other=0.0)
        gate_f += tl.load(
            hidden_bias + (hidden_size + cols) * hidden_bias_stride,
            mask=mask,
            other=0.0,
        )
        gate_c += tl.load(
            hidden_bias + (2 * hidden_size + cols) * hidden_bias_stride,
            mask=mask,
            other=0.0,
        )
        gate_o += tl.load(
            hidden_bias + (3 * hidden_size + cols) * hidden_bias_stride,
            mask=mask,
            other=0.0,
        )
        if IS_FP16:
            gate_i = gate_i.to(tl.float16)
            gate_f = gate_f.to(tl.float16)
            gate_c = gate_c.to(tl.float16)
            gate_o = gate_o.to(tl.float16)
        if IS_BF16:
            gate_i = gate_i.to(tl.bfloat16)
            gate_f = gate_f.to(tl.bfloat16)
            gate_c = gate_c.to(tl.bfloat16)
            gate_o = gate_o.to(tl.bfloat16)

    if not IS_FP64:
        gate_i = gate_i.to(tl.float32)
        gate_f = gate_f.to(tl.float32)
        gate_c = gate_c.to(tl.float32)
        gate_o = gate_o.to(tl.float32)
    input_gate = tl.sigmoid(gate_i)
    forget_gate = tl.sigmoid(gate_f)
    cell_gate = tl_extra_shim.tanh(gate_c)
    output_gate = tl.sigmoid(gate_o)
    if IS_FP16:
        input_gate = input_gate.to(tl.float16)
        forget_gate = forget_gate.to(tl.float16)
        cell_gate = cell_gate.to(tl.float16)
        output_gate = output_gate.to(tl.float16)
    if IS_BF16:
        input_gate = input_gate.to(tl.bfloat16)
        forget_gate = forget_gate.to(tl.bfloat16)
        cell_gate = cell_gate.to(tl.bfloat16)
        output_gate = output_gate.to(tl.bfloat16)

    state_offsets = rows * cx_stride_0 + cols * cx_stride_1
    cx_value = tl.load(cx + state_offsets, mask=mask, other=0.0)
    cy_value = tl.load(
        cy + rows * cy_stride_0 + cols * cy_stride_1,
        mask=mask,
        other=0.0,
    )
    cy_tanh = tl_extra_shim.tanh(cy_value if IS_FP64 else cy_value.to(tl.float32))
    if IS_FP16:
        cy_tanh = cy_tanh.to(tl.float16)
    if IS_BF16:
        cy_tanh = cy_tanh.to(tl.bfloat16)

    if HAS_GRAD_HY:
        grad_hy_value = tl.load(
            grad_hy + rows * grad_hy_stride_0 + cols * grad_hy_stride_1,
            mask=mask,
            other=0.0,
        )
        grad_output_seed = grad_hy_value * cy_tanh
        grad_cell_seed = grad_hy_value * output_gate
        if IS_FP16:
            grad_output_seed = grad_output_seed.to(tl.float16)
            grad_cell_seed = grad_cell_seed.to(tl.float16)
        if IS_BF16:
            grad_output_seed = grad_output_seed.to(tl.bfloat16)
            grad_cell_seed = grad_cell_seed.to(tl.bfloat16)
        if not IS_FP64:
            grad_output_seed = grad_output_seed.to(tl.float32)
            grad_cell_seed = grad_cell_seed.to(tl.float32)
            output_gate_fp = output_gate.to(tl.float32)
            cy_tanh_fp = cy_tanh.to(tl.float32)
        else:
            output_gate_fp = output_gate
            cy_tanh_fp = cy_tanh
        grad_output = grad_output_seed * (1.0 - output_gate_fp) * output_gate_fp
        grad_cell = grad_cell_seed * (1.0 - cy_tanh_fp * cy_tanh_fp)
        if IS_FP16:
            grad_output = grad_output.to(tl.float16)
            grad_cell = grad_cell.to(tl.float16)
        if IS_BF16:
            grad_output = grad_output.to(tl.bfloat16)
            grad_cell = grad_cell.to(tl.bfloat16)
        if HAS_GRAD_CY:
            grad_cy_value = tl.load(
                grad_cy + rows * grad_cy_stride_0 + cols * grad_cy_stride_1,
                mask=mask,
                other=0.0,
            )
            grad_cell += grad_cy_value
            if IS_FP16:
                grad_cell = grad_cell.to(tl.float16)
            if IS_BF16:
                grad_cell = grad_cell.to(tl.bfloat16)
    else:
        grad_output = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)
        grad_cell = tl.load(
            grad_cy + rows * grad_cy_stride_0 + cols * grad_cy_stride_1,
            mask=mask,
            other=0.0,
        )

    grad_input_seed = grad_cell * cell_gate
    grad_forget_seed = grad_cell * cx_value
    grad_candidate_seed = grad_cell * input_gate
    next_grad_cx = grad_cell * forget_gate
    if IS_FP16:
        grad_input_seed = grad_input_seed.to(tl.float16)
        grad_forget_seed = grad_forget_seed.to(tl.float16)
        grad_candidate_seed = grad_candidate_seed.to(tl.float16)
        next_grad_cx = next_grad_cx.to(tl.float16)
    if IS_BF16:
        grad_input_seed = grad_input_seed.to(tl.bfloat16)
        grad_forget_seed = grad_forget_seed.to(tl.bfloat16)
        grad_candidate_seed = grad_candidate_seed.to(tl.bfloat16)
        next_grad_cx = next_grad_cx.to(tl.bfloat16)

    if not IS_FP64:
        grad_input_seed = grad_input_seed.to(tl.float32)
        grad_forget_seed = grad_forget_seed.to(tl.float32)
        grad_candidate_seed = grad_candidate_seed.to(tl.float32)
        input_gate_fp = input_gate.to(tl.float32)
        forget_gate_fp = forget_gate.to(tl.float32)
        cell_gate_fp = cell_gate.to(tl.float32)
    else:
        input_gate_fp = input_gate
        forget_gate_fp = forget_gate
        cell_gate_fp = cell_gate
    grad_input = grad_input_seed * (1.0 - input_gate_fp) * input_gate_fp
    grad_forget = grad_forget_seed * (1.0 - forget_gate_fp) * forget_gate_fp
    grad_candidate = grad_candidate_seed * (1.0 - cell_gate_fp * cell_gate_fp)

    output_offsets = rows * (4 * hidden_size) + cols
    tl.store(grad_gates + output_offsets, grad_input, mask=mask)
    tl.store(grad_gates + output_offsets + hidden_size, grad_forget, mask=mask)
    tl.store(
        grad_gates + output_offsets + 2 * hidden_size,
        grad_candidate,
        mask=mask,
    )
    tl.store(
        grad_gates + output_offsets + 3 * hidden_size,
        grad_output,
        mask=mask,
    )
    tl.store(grad_cx + rows * hidden_size + cols, next_grad_cx, mask=mask)


@libentry()
@triton.jit
def _lstm_bias_backward_kernel(
    grad_gates,
    grad_bias,
    batch_size,
    gate_size,
    BLOCK_BATCH: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    gate_offset = tl.program_id(0)
    batch_offsets = tl.arange(0, BLOCK_BATCH)
    if IS_FP64:
        accumulator = tl.zeros((BLOCK_BATCH,), dtype=tl.float64)
    else:
        accumulator = tl.zeros((BLOCK_BATCH,), dtype=tl.float32)

    for batch_start in range(0, batch_size, BLOCK_BATCH):
        rows = batch_start + batch_offsets
        mask = rows < batch_size
        values = tl.load(
            grad_gates + rows * gate_size + gate_offset,
            mask=mask,
            other=0.0,
        )
        if IS_FP64:
            accumulator += values.to(tl.float64)
        else:
            accumulator += values.to(tl.float32)
    tl.store(grad_bias + gate_offset, tl.sum(accumulator, axis=0))


def _validate_inputs(
    grad_hy, grad_cy, input_gates, hidden_gates, input_bias, hidden_bias, cx, cy
):
    if any(tensor.ndim != 2 for tensor in (input_gates, hidden_gates, cx, cy)):
        raise RuntimeError("LSTM cell backward expects 2-D state and gate tensors")
    if cx.shape != cy.shape:
        raise RuntimeError("cx and cy must have the same shape")
    batch_size, hidden_size = cx.shape
    expected_gate_shape = (batch_size, 4 * hidden_size)
    if (
        input_gates.shape != expected_gate_shape
        or hidden_gates.shape != expected_gate_shape
    ):
        raise RuntimeError(
            "input_gates and hidden_gates must have shape "
            f"({batch_size}, {4 * hidden_size})"
        )
    for name, grad in (("grad_hy", grad_hy), ("grad_cy", grad_cy)):
        if grad is not None and grad.shape != cx.shape:
            raise RuntimeError(f"{name} and cx must have the same shape")
    gate_size = 4 * hidden_size
    for name, bias in (("input_bias", input_bias), ("hidden_bias", hidden_bias)):
        if bias is not None and (bias.ndim != 1 or bias.numel() != gate_size):
            raise RuntimeError(f"{name} must have shape ({gate_size},)")


def _differentiable_lstm_cell_backward(
    grad_hy, grad_cy, input_gates, hidden_gates, input_bias, hidden_bias, cx, cy
):
    """ATen's composite path, retained when constructing a higher-order graph."""
    gates = input_gates + hidden_gates
    if input_bias is not None:
        gates = gates + input_bias
    if hidden_bias is not None:
        gates = gates + hidden_bias
    hidden_size = cx.shape[1]
    gate_i = gates[:, :hidden_size]
    gate_f = gates[:, hidden_size : 2 * hidden_size]
    gate_c = gates[:, 2 * hidden_size : 3 * hidden_size]
    gate_o = gates[:, 3 * hidden_size :]
    input_gate = gate_i.sigmoid()
    forget_gate = gate_f.sigmoid()
    cell_gate = gate_c.tanh()
    output_gate = gate_o.sigmoid()

    cy_tanh = cy.tanh()
    if grad_hy is not None:
        grad_output = grad_hy * cy_tanh
        grad_output = grad_output * (1.0 - output_gate) * output_gate
        grad_cell = grad_hy * output_gate
        grad_cell = grad_cell * (1.0 - cy_tanh * cy_tanh)
        if grad_cy is not None:
            grad_cell = grad_cell + grad_cy
    else:
        grad_output = torch.zeros_like(cx, memory_format=torch.contiguous_format)
        grad_cell = grad_cy

    grad_input = grad_cell * cell_gate
    grad_forget = grad_cell * cx
    grad_candidate = grad_cell * input_gate
    grad_cx = grad_cell * forget_gate
    grad_input = grad_input * (1.0 - input_gate) * input_gate
    grad_forget = grad_forget * (1.0 - forget_gate) * forget_gate
    grad_candidate = grad_candidate * (1.0 - cell_gate * cell_gate)
    grad_gates = torch.cat(
        (grad_input, grad_forget, grad_candidate, grad_output), dim=1
    )
    grad_bias = grad_gates.sum(0) if input_bias is not None else None
    return grad_gates, grad_gates, grad_cx, grad_bias, grad_bias


def _thnn_differentiable_lstm_cell_backward(
    grad_hy, grad_cy, input_gates, hidden_gates, input_bias, hidden_bias, cx, cy
):
    """Compute the five differentiable LSTM-cell backward outputs."""
    logger.debug("GEMS _THNN_DIFFERENTIABLE_LSTM_CELL_BACKWARD")

    # Native returns a tuple of undefined tensors without inspecting the other
    # arguments when neither output gradient is defined.
    if grad_hy is None and grad_cy is None:
        return None, None, None, None, None

    _validate_inputs(
        grad_hy,
        grad_cy,
        input_gates,
        hidden_gates,
        input_bias,
        hidden_bias,
        cx,
        cy,
    )
    differentiable_inputs = (
        grad_hy,
        grad_cy,
        input_gates,
        hidden_gates,
        input_bias,
        hidden_bias,
        cx,
        cy,
    )
    if torch.is_grad_enabled() and any(
        value is not None and value.requires_grad for value in differentiable_inputs
    ):
        return _differentiable_lstm_cell_backward(*differentiable_inputs)

    batch_size, hidden_size = cx.shape
    gate_size = 4 * hidden_size
    grad_gates = torch.empty(
        (batch_size, gate_size),
        dtype=input_gates.dtype,
        device=input_gates.device,
    )
    grad_cx = torch.empty_like(cx, memory_format=torch.contiguous_format)

    n_elements = batch_size * hidden_size
    if n_elements != 0:
        block_size = 256
        input_bias_arg = input_bias if input_bias is not None else input_gates
        hidden_bias_arg = hidden_bias if hidden_bias is not None else hidden_gates
        grad_hy_arg = grad_hy if grad_hy is not None else cx
        grad_cy_arg = grad_cy if grad_cy is not None else cx
        with torch_device_fn.device(input_gates.device):
            _lstm_cell_backward_kernel[(triton.cdiv(n_elements, block_size),)](
                grad_hy_arg,
                grad_cy_arg,
                input_gates,
                hidden_gates,
                input_bias_arg,
                hidden_bias_arg,
                cx,
                cy,
                grad_gates,
                grad_cx,
                batch_size,
                hidden_size,
                grad_hy_arg.stride(0),
                grad_hy_arg.stride(1),
                grad_cy_arg.stride(0),
                grad_cy_arg.stride(1),
                input_gates.stride(0),
                input_gates.stride(1),
                hidden_gates.stride(0),
                hidden_gates.stride(1),
                input_bias_arg.stride(0),
                hidden_bias_arg.stride(0),
                cx.stride(0),
                cx.stride(1),
                cy.stride(0),
                cy.stride(1),
                BLOCK_SIZE=block_size,
                HAS_GRAD_HY=grad_hy is not None,
                HAS_GRAD_CY=grad_cy is not None,
                HAS_INPUT_BIAS=input_bias is not None,
                HAS_HIDDEN_BIAS=hidden_bias is not None,
                IS_FP64=input_gates.dtype == torch.float64,
                IS_FP16=input_gates.dtype == torch.float16,
                IS_BF16=input_gates.dtype == torch.bfloat16,
            )

    # ATen intentionally keys both optional bias gradients on input_bias.
    if input_bias is None:
        return grad_gates, grad_gates, grad_cx, None, None

    grad_bias = torch.empty(
        (gate_size,), dtype=input_gates.dtype, device=input_gates.device
    )
    if gate_size != 0:
        with torch_device_fn.device(input_gates.device):
            _lstm_bias_backward_kernel[(gate_size,)](
                grad_gates,
                grad_bias,
                batch_size,
                gate_size,
                BLOCK_BATCH=256,
                IS_FP64=input_gates.dtype == torch.float64,
            )
    return grad_gates, grad_gates, grad_cx, grad_bias, grad_bias
